// GENERATED by scripts/sync-github.mjs — do not edit by hand.
// Every number here is pulled from the GitHub API. Refresh with `npm run sync:github`.

export interface GithubQuarter {
  /** Calendar quarter, e.g. `Q1 ’26`. */
  q: string;
  /** GitHub's own contribution-calendar total for the quarter. */
  contributions: number;
  /** Share of the quarter's attributed commits, by repository primary language. */
  rust: number;
  typescript: number;
  java: number;
  /** Everything outside the three tracked languages. */
  other: number;
}

export const GITHUB_STATS = {
  login: "alessandrobrunoh",
  generatedAt: "2026-08-25",
  /** Public + private contributions over the trailing 12 months, as GitHub counts them. */
  lastYearContributions: 2035,
  publicRepos: 49,
  totalStars: 26,
  /** Stars per public repository, for the ones that have any. */
  stars: {
    "DioxusTest": 1,
    "ducklake-orm": 2,
    "gpuiTest": 1,
    "KetchApp-Auth-Api": 1,
    "KetchApp-Kafka": 1,
    "LeptosTest": 1,
    "leptos_styles": 1,
    "Mnemosyne": 10,
    "openai-proxy-for-antigravity": 1,
    "Progetto-Big-Data": 1,
    "Progetto-Fondamenti-Web": 1,
    "Progetto-Ingegneria-Web": 1,
    "Progetto-Machine-Learning": 1,
    "ReactTest": 1,
    "Semantic-Delta-Protocol": 1,
    "SycamoreTest": 1
  } as Record<string, number>,
  series: [
    {
      "q": "Q1 ’24",
      "contributions": 4,
      "rust": 0,
      "typescript": 0,
      "java": 0,
      "other": 100
    },
    {
      "q": "Q2 ’24",
      "contributions": 42,
      "rust": 0,
      "typescript": 0,
      "java": 0,
      "other": 100
    },
    {
      "q": "Q3 ’24",
      "contributions": 69,
      "rust": 0,
      "typescript": 0,
      "java": 0,
      "other": 100
    },
    {
      "q": "Q4 ’24",
      "contributions": 40,
      "rust": 0,
      "typescript": 0,
      "java": 0,
      "other": 100
    },
    {
      "q": "Q1 ’25",
      "contributions": 32,
      "rust": 0,
      "typescript": 0,
      "java": 0,
      "other": 100
    },
    {
      "q": "Q2 ’25",
      "contributions": 25,
      "rust": 0,
      "typescript": 0,
      "java": 20,
      "other": 80
    },
    {
      "q": "Q3 ’25",
      "contributions": 539,
      "rust": 15,
      "typescript": 0,
      "java": 40,
      "other": 45
    },
    {
      "q": "Q4 ’25",
      "contributions": 235,
      "rust": 25,
      "typescript": 0,
      "java": 0,
      "other": 75
    },
    {
      "q": "Q1 ’26",
      "contributions": 812,
      "rust": 96,
      "typescript": 3,
      "java": 0,
      "other": 1
    },
    {
      "q": "Q2 ’26",
      "contributions": 293,
      "rust": 28,
      "typescript": 58,
      "java": 0,
      "other": 14
    },
    {
      "q": "Q3 ’26",
      "contributions": 466,
      "rust": 99,
      "typescript": 0,
      "java": 0,
      "other": 1
    }
  ] satisfies GithubQuarter[],
  now: "Q3 ’26",
} as const;
