import { GITHUB_STATS } from "./github-stats";
import type { SiteData } from "./site.types";

export const EN: SiteData = {
  PROFILE: {
    name: "Alessandro Bruno",
    role: "Software Engineer — in production",
    shortRole: "Backend · Web & mobile · Developer tools",
    headline: "I build the software, and I work out what to build with the people who have to use it.",
    location: "Bologna, Italy",
    github: "https://github.com/alessandrobrunoh",
    website: "https://alessandrobrunoh.it",
    email: "alessandro.brunoh@gmail.com",
    x: "",
    avatar: "/avatar.jpg",
    company: { name: "Luna S.r.l.", href: "https://lunapartner.it" },
    bio: "I'm a software engineer in Bologna. I get curious about how a system actually works, and I don't like leaving a problem half done. At Luna S.r.l. I work on client software that is already in production. A good part of that job is sitting with the client and deciding, together, what is worth building. On my own time I make the tools I was missing. Trama is the main one. I graduated from the University of Bologna in 2026, with a thesis on real-time telemetry called PETRA.",
    availability: "Open to Software Engineer and Forward Deployed Engineer roles — backend, full-stack or customer-facing; remote or hybrid in Italy, available with notice. EU citizen.",
  },

  TOC: [
    { n: "01", href: "#intro", label: "Intro" },
    { n: "02", href: "#experience", label: "Experience" },
    { n: "03", href: "#work", label: "Work" },
    { n: "04", href: "#approach", label: "How I work" },
    { n: "05", href: "#contact", label: "Contact" },
  ],

  COMPANY: {
    name: "Luna S.r.l.",
    href: "https://lunapartner.it",
    location: "Bologna, Italy",
    summary:
      "At Luna S.r.l. I work across client software: a fleet platform with Java/Spring Boot, Angular and React Native; production services in Rust; and a new operator console with Spring Boot APIs and a React interface. Before I implement, I talk the options through with the client: what to build now, what can wait, and what each choice costs the people running the platform. The code is reviewed by a senior.",
  },

  ROLES: [
    {
      title: "Software Developer",
      dates: "Jun 2026 — present",
      current: true,
      caseId: "event-platform",
      bullets: [
        "Embedded on a client's production platform: event-driven Rust services that process their workloads — async consumers on Valkey Streams, payloads on S3.",
        "Made the services observable end to end: traces and logs through OpenTelemetry into Grafana, Loki and Tempo, so problems are traced across services instead of guessed.",
        "Building a new operator console end to end — Spring Boot APIs and a React UI for the people who run the platform day to day.",
        "I go through the implementation choices with the client before writing them: what to build, what to leave, and what fails for the people who operate the platform if we pick wrong.",
      ],
      tags: ["Rust", "Tokio", "Valkey Streams", "S3", "OpenTelemetry", "Spring Boot", "React"],
    },
    {
      title: "Software Developer Intern",
      dates: "Sep 2025 — Jun 2026",
      current: false,
      bullets: [
        "Fleet platform in Spring Boot, Angular and React Native, with live updates over WebSockets.",
        "Moved onto a client's production Rust backend after two months, shipping under senior code review.",
        "Small, reviewable diffs on stacked branches — the habit that makes changes safe to land in someone else's system.",
      ],
      tags: ["Spring Boot", "Angular", "React Native", "WebSocket", "Rust"],
    },
  ],

  EDUCATION: {
    school: "University of Bologna — Cesena Campus",
    degree: "B.Sc. Computer Systems Technologies",
    native: "Tecnologie dei Sistemi Informatici",
    dates: "Graduated 10 Jul 2026",
    thesis: "Design and Development of PETRA, an Event-Driven Platform for Real-Time Asynchronous Telemetry and Analysis",
    // Drop the PDF in /public and set this to "/petra-thesis.pdf" to make it readable.
    thesisHref: "",
  },

  CONTRIBUTIONS: [
    {
      status: "Published",
      title: "ducklake-orm",
      repo: "crates.io",
      href: "https://crates.io/crates/ducklake-orm",
      note: "Rust ORM with derive macros, query builders, pooling, migrations and DuckLake time travel.",
    },
    {
      status: "Open",
      title: "Port forwarding UI and live SSH forwards",
      repo: "zed-industries/zed",
      href: "https://github.com/zed-industries/zed/pull/55248",
      note: "Add or remove forwards on remote sessions without reconnecting.",
    },
    {
      status: "Merged",
      title: "JDL syntax highlighting",
      repo: "zed-industries/extensions",
      href: "https://github.com/zed-industries/extensions/pull/3339",
      note: "A small editor extension.",
    },
  ],

  PROJECTS: [
    {
      id: "trama",
      name: "Trama",
      blurb: "The missing layer between a reported problem and a shipped fix. Issues stay. A workstream carries the outcome, with the decisions and the artifacts attached.",
      problem: "Issue trackers assume one ticket is one person and one pull request. That falls apart when several bugs share a cause, the work crosses repositories, and a coding agent does part of the job. The reason for a choice ends up in a chat nobody can find a month later.",
      decisions: [
        {
          title: "Keep the issue. Add the workstream.",
          context: "Teams already know tickets. Replacing that on day one is how a new tool gets ignored. The ticket is still a good way to say that something is wrong. It is a bad way to say how a team, or a team and an agent, will actually fix several things at once.",
          choice: "An issue stays the unit of demand, keyed like BUG-142. A workstream is the outcome you commit to, keyed like AUTH-42, and it can hold the issues that share a root cause. Its state comes from facts: criteria met, pull requests merged, questions still open. You can still pin it by hand when you need to.",
        },
        {
          title: "Don't copy the coding session into the tracker",
          context: "The implementation already lives in the editor, the agent thread and Git. A second copy goes stale, and it makes people write down work they already did.",
          choice: "Trama keeps what someone still needs if they never open that thread: the objective, who is accountable, the decision, the artifact. The discussion stays where the work happened. A decision is promoted only when it should outlive the session. If a feature feels like documenting Delta again, it doesn't belong.",
        },
        {
          title: "No invented progress",
          context: "A percentage looks precise and usually isn't. Agent telemetry and an '84% done' bar are bookkeeping, not a fact you can check.",
          choice: "Show what you can observe: issues linked and resolved, pull requests open or merged, CI, a review waiting. Suggest a state change when the facts support it. Don't pretend the tool knows more than it measured.",
        },
      ],
      href: "https://github.com/alessandrobrunoh/trama",
      stars: GITHUB_STATS.stars["trama"] ?? 0,
      lang: "TypeScript",
      meta: "Live",
      featured: true,
      year: "2026",
      demo: "https://trama.alessandrobrunoh.it",
      stack: ["Angular", "NestJS", "PostgreSQL", "Rust"],
      highlights: [
        "Issues stay first-class. A workstream groups the ones that share an outcome",
        "Decisions and artifacts, from pull requests to deploys, stay next to that outcome",
        "Agents are members. An attention queue shows where a person still has to decide",
        "One Postgres and three small images. Self-hosted, not a platform you have to rent",
      ],
      learned:
        "The hard part was the boundary. Trama helps when it explains the outcome, and it gets in the way the moment it asks you to write down work you already did somewhere else.",
      body: "Trama is a source-available coordination layer for teams that ship with people and coding agents. The name is Italian for weft: the thread that runs across a loom and turns separate strands into one fabric. Issues remain the familiar way to record a bug, a request or a finding. A workstream is the new unit, the outcome a team commits to, with acceptance criteria, contributors and dependencies. Decisions are records in their own right, not a paragraph lost in a thread. Artifacts are the proof: pull requests, builds, test reports, deployments, with CI and review state attached. An agent that is blocked asks a person and waits, instead of guessing. Humans and agents are both actors, with scoped tokens and a trail. GitHub, GitLab and Bitbucket feed it pull requests and webhooks. A Rust MCP server, about ninety tools, lets an agent read and change the workspace without holding any data of its own. The API stays the authority.",
    },
    {
      id: "eivar",
      name: "Eivar-Online",
      blurb: "Multiplayer prototype: server-authoritative Rust simulation, replicated state, client-side prediction.",
      problem: "How do you keep a shared game world consistent while making it feel responsive to each player? I am exploring authoritative simulation, replicated state and client-side prediction in Rust.",
      href: "https://github.com/alessandrobrunoh/Eivar-Online",
      stars: GITHUB_STATS.stars["Eivar-Online"] ?? 0,
      lang: "Rust",
      meta: "In progress",
      featured: true,
      year: "2026",
      stack: ["Bevy", "SpacetimeDB", "WebAssembly", "Distributed state"],
      highlights: [
        "Server-authoritative simulation with client-side prediction",
        "Replicated state through a SpacetimeDB module compiled to WebAssembly",
        "Loot, gathering, crafting and player markets as bounded domain events",
      ],
      learned:
        "How ECS design, replicated state and client-side prediction fit together: the server enforces the rules while the client keeps play responsive.",
      body: "An open-source multiplayer prototype written in Rust, with Bevy ECS for gameplay and SpacetimeDB for replicated state. I work on simulation, client-side prediction and game mechanics: crowd-control, ability kits, loot, gathering, crafting and player markets. A place to explore game development, networking and WebAssembly together.",
    },
    {
      id: "mnemosyne",
      name: "Mnemosyne",
      blurb: "Local-first semantic history for source code: symbols and structural changes via Tree-sitter, not line diffs — queryable by AI agents over MCP.",
      problem: "Git only remembers what you commit. Between commits work gets lost, and line diffs cannot say which function changed or how. I wanted a local history that understands code structure — and that AI tools can query.",
      href: "https://github.com/alessandrobrunoh/Mnemosyne",
      stars: GITHUB_STATS.stars["Mnemosyne"] ?? 0,
      lang: "Rust",
      meta: "Semantic history",
      featured: true,
      year: "2026",
      stack: ["Tree-sitter", "redb", "Content-addressed storage", "MCP"],
      highlights: [
        "Tracks symbols and structural changes instead of line-based diffs",
        "Daemon, CLI and TUI over a content-addressed storage workspace",
        "Exposed to AI tools through MCP",
      ],
      learned: "Shipping a daemon people actually run. Content-addressed storage, a TUI, and the discipline of keeping every byte on-device.",
      body: "The local-history tool I wanted as a daily driver. A daemon watches saves, a TUI and CLI search and restore, and nothing leaves the machine. Still the project that taught me how to ship a Rust tool people actually run.",
    },
    {
      id: "ducklake",
      name: "ducklake-orm",
      blurb: "Rust ORM for DuckDB and DuckLake, published on crates.io — derive macros, query builders, pooling, migrations, time travel.",
      problem: "DuckDB and DuckLake are great for analytics, but using them from Rust meant hand-written SQL and loosely typed results. I wanted the ergonomics of an ORM without hiding what the database does well.",
      decisions: [
        {
          title: "Typed errors and discoverable defaults",
          context: "Analytical storage is powerful, but power alone does not make a tool pleasant to use on an ordinary workday.",
          choice: "Typed errors, defaults you can discover from the API, and migrations inside the library — so a new user can predict what happens next without opening the implementation.",
        },
        {
          title: "Know where the abstraction stops",
          context: "An ORM that hides everything makes the reader pay its complexity tax.",
          choice: "Derive macros and query builders cover the common path — filters, ordering, limits, counts, fetch_one. Beyond that the database speaks for itself, including DuckLake time travel.",
        },
      ],
      href: "https://github.com/alessandrobrunoh/ducklake-orm",
      stars: GITHUB_STATS.stars["ducklake-orm"] ?? 0,
      lang: "Rust",
      meta: "crates.io",
      featured: true,
      year: "2026",
      stack: ["Rust", "DuckDB", "proc-macro", "SQL"],
      highlights: [
        "Derive macros map structs to tables with zero boilerplate",
        "Type-safe filters, order_by, limit, count, fetch_one",
        "Pooling, migrations, and DuckLake time travel",
      ],
      learned: "The layer under the query: typed boundaries, data ergonomics, and what it takes to make analytical storage feel like a product.",
      body: "A lightweight Rust ORM for DuckDB, built to make analytical storage feel approachable without hiding the useful parts. The work is about typed boundaries, data ergonomics, and the small API decisions that make a tool pleasant to keep using.",
    },
    {
      id: "weaklings",
      name: "Weaklings-Manager",
      blurb: "Self-hosted Albion guild platform — bank, loot splits, battle analytics, Discord login.",
      problem: "A gaming guild ran its bank, loot splits and events on spreadsheets and Discord messages. It needed one tool its officers could trust, with access tied to the roles people already had on Discord.",
      href: "https://github.com/alessandrobrunoh/Weaklings-Manager",
      stars: GITHUB_STATS.stars["Weaklings-Manager"] ?? 0,
      lang: "Angular",
      meta: "Axum API",
      featured: false,
      year: "2026",
      stack: ["Axum", "PostgreSQL", "Angular", "Discord"],
      highlights: ["Guild bank and loot splits", "Event sessions with battle analytics", "Discord login with role-based access"],
      learned: "A real domain with real users: auth, bank, compositions, and a bot that had to stay up for a guild — not a demo.",
      body: "A Rust/Axum API, an Angular dashboard, and a Discord bot — covering bank, compositions, siphoned-energy tracking, and live Albion data. Built for a guild that needed a real tool, not a spreadsheet.",
    },
    {
      id: "ketchapp",
      name: "KetchApp",
      blurb: "Study productivity as microservices. Pomodoro, AI plans, async notifications.",
      problem: "A university team needed a study app with Pomodoro sessions, AI-generated plans and notifications — built by several people at once without stepping on each other.",
      href: "https://github.com/orgs/ketchapp-for-study",
      lang: "Java",
      meta: "Org",
      featured: false,
      year: "2025",
      stack: ["Rust", "Java", "Kafka", "Auth"],
      highlights: ["Auth API in Rust", "Kafka-backed notifications", "Split services instead of a monolith"],
      learned: "Where a monolith breaks. Auth in Rust, notifications on Kafka, and the seams you only see once the pieces move.",
      body: "University team project that became my first real microservices cut: a Rust auth API, a Java Kafka path, and async notifications for Pomodoro and study plans. The org still holds the split.",
    },
    {
      id: "briscola",
      name: "Briscola Online",
      blurb: "Real-time Briscola over WebSockets. Full-stack multiplayer.",
      problem: "Friends wanted to play Briscola online, together and in real time, at a table that behaved like the real one.",
      href: "https://github.com/alessandrobrunoh/Progetto-Ingegneria-Web",
      stars: GITHUB_STATS.stars["Progetto-Ingegneria-Web"] ?? 0,
      lang: "Vue",
      meta: "Web",
      featured: false,
      year: "2024",
      stack: ["Vue", "WebSocket", "Node"],
      highlights: ["Live multiplayer matches", "Responsive table UI", "Persistent game data"],
      learned: "The first time a WebSocket had to stay honest for friends at a table — state, turns, and a UI that could lose.",
      body: "Web engineering coursework that had to actually play. Real-time Briscola over WebSockets, a Vue frontend, and enough backend to keep a match honest. The first time I shipped something friends sat down and used.",
    },
    {
      id: "sdp",
      name: "Semantic Delta Protocol",
      blurb: "Code changes at the AST level — Tree-sitter and structural hashing.",
      problem: "Line-based diffs lose track of code when it moves or gets renamed. Editors and tools need to follow a function through a refactor, not a line number.",
      href: "https://github.com/alessandrobrunoh/Semantic-Delta-Protocol",
      stars: GITHUB_STATS.stars["Semantic-Delta-Protocol"] ?? 0,
      lang: "Rust",
      meta: "Protocol",
      featured: false,
      year: "2026",
      stack: ["Rust", "Tree-sitter", "JSON-RPC"],
      highlights: ["Symbols instead of line diffs", "Structural hashing that survives refactors", "JSON-RPC surface for editors"],
      learned: "Identity that survives a rename. Tree-sitter walks the AST; hashes keep a function the same function.",
      body: "A protocol for tracking changes at the function and class level, not the line. Tree-sitter walks the AST; structural hashes keep identity through a rename. The research sibling of Mnemosyne.",
    },
    {
      id: "vapt",
      name: "VAPT Research",
      blurb: "Security report on a fork of OWASP Juice Shop.",
      problem: "A security course asked for a real assessment, not a scan dump: find what is actually exploitable in a deliberately vulnerable app and explain how to fix it.",
      href: "https://github.com/alessandrobrunoh/Relazione-Sicurezza-Privacy",
      lang: "TypeScript",
      meta: "Research",
      featured: false,
      year: "2025",
      stack: ["TypeScript", "OWASP", "VAPT"],
      highlights: ["Forked Juice Shop as the target", "Structured findings, not a scan dump", "Coursework that had to read like a report"],
      learned: "Scope, exploit, impact, fix. Writing like a report, not a leaderboard of CVEs.",
      body: "A vulnerability assessment against a known-broken app, written up as a real report. The point was the method: scope, exploit, impact, fix — not a leaderboard of CVEs.",
    },
  ],

  STACK: {
    groups: [
      {
        name: "Rust",
        level: "Proficient",
        items: "Tokio · Axum · SQLx · Tree-sitter · Bevy",
        also: "Actix, SeaORM, Diesel, clap, ratatui, Leptos, Dioxus, GPUI, wasm-bindgen",
      },
      {
        name: "TypeScript",
        level: "Competent",
        items: "Angular · React · React Native · Node",
        also: "Svelte, Expo, NestJS, Tailwind CSS",
      },
      {
        name: "Java & Python",
        level: "Competent",
        items: "Spring Boot · Hibernate · Maven",
        also: "JHipster, Gradle, Kafka, Python",
      },
      {
        name: "Infrastructure",
        level: "",
        items: "Docker · PostgreSQL · Valkey · S3 · OpenTelemetry · Grafana",
        also: "Linux, Loki, Tempo, Alloy, Redis, DuckLake, Kubernetes",
      },
    ],
  },

  FUTURE_PROJECTS: [
    {
      id: "solana-dex",
      name: "Mini DEX on Solana",
      blurb: "On-chain order matching under blockchain constraints.",
      href: "",
      lang: "Solana",
      meta: "Planned",
      year: "Next",
      stack: ["Rust", "Solana", "Anchor"],
      highlights: [
        "On-chain order book with matching logic in a program",
        "Account-model constraints instead of a free-form database",
        "Compute-budget limits force every instruction to be lean",
      ],
      learned: "How on-chain matching holds up under Solana's account model and compute limits — not just the theory.",
      body: "A DEX order matcher written as a Solana program. The interesting part isn't the matching logic — it's building it inside an account model and compute budget that make you justify every byte and every instruction.",
    },
    {
      id: "btree-db",
      name: "Mini database engine with a B-Tree",
      blurb: "Storage internals — the layer beneath ORMs.",
      href: "https://github.com/alessandrobrunoh/mini-db-btree",
      lang: "Rust",
      meta: "Planned",
      year: "Next",
      stack: ["Rust", "B-Tree", "Storage"],
      highlights: [
        "Page splits, reads, and writes on raw disk pages",
        "No ORM in between — the storage layer itself",
        "A ground-up look at what ducklake-orm sits on top of",
      ],
      learned: "What a B-Tree actually does on disk — page splits, reads, and writes — instead of just calling one through an ORM.",
      body: "A small database engine built around a B-Tree, from scratch. After publishing an ORM, this is the layer beneath it: how data actually gets organized, split, and found on disk.",
    },

  ],

  CASES: [
    {
      id: "event-platform",
      title: "An event-driven platform for a client",
      role: "Software Developer · Luna S.r.l.",
      era: "2025 — present",
      blurb: "Working inside a client's production backend: Rust consumers on Valkey Streams, payloads on S3, end-to-end tracing, and an operator console for the people who run it.",
      problem: "A client runs its workloads through an event-driven backend. Work arrives as events, payloads live on S3, and every event has to be processed exactly once in effect — under load, with retries — while the people operating the platform need to see what happened when something goes wrong.",
      built: [
        "Async Rust consumers on Valkey Streams that read, handle and acknowledge events, with payloads on S3.",
        "Tracing and logging through OpenTelemetry into Grafana, Loki and Tempo, so a single event can be followed across services.",
        "A new operator console — Spring Boot APIs and a React UI — for the people who run the platform day to day.",
        "Everything shipped as small, reviewable diffs under senior code review.",
      ],
      decisions: [
        {
          title: "Acknowledge after the side effect, not after the read",
          context: "I came from a request/response world, where a call is answered and forgotten. On an event bus I treated “delivered” and “processed” as the same thing. They are not: the gap between them is where retries, duplicates and ordering bugs live.",
          choice: "Make each consumer an explicit small state machine — read, handle, acknowledge — and acknowledge only once the work has actually happened. Retries stopped being edge cases and became part of the design.",
          code: "// delivered is not processed\nlet message = stream.read().await?;\nif worker.handle(&message).await? {\n    stream.ack(message.id).await?;\n}",
        },
        {
          title: "Observability before trust",
          context: "An event bus fails quietly: a message that was never processed can look exactly like one that was.",
          choice: "Traces and logs went in through OpenTelemetry, into Grafana, Loki and Tempo, before more was built on top of the bus — so every event can be followed end to end, and problems are found from evidence rather than guesses.",
        },
        {
          title: "Choose with the client, not after the fact",
          context: "This is someone else's production system. A design that looks clean to me and wrong to the people who run it is not a good design, and I don't see the cost of a choice as clearly as they do.",
          choice: "I put the options on the table with them: what to build now, what can wait, and what fails if we guess. We pick one, then I write it. The technical decisions above came out of those conversations, not from a ticket thrown over a wall.",
        },
      ],
      learned: "Delivery is not processing. Once the transitions are explicit and observable, an event-driven system becomes something you can reason about, and explain to the people who depend on it. The same is true of the choices: they are easier to defend when the client was in the room when we made them.",
      stack: [
        "Rust",
        "Tokio",
        "Valkey Streams",
        "S3",
        "OpenTelemetry",
        "Grafana",
        "Loki",
        "Tempo",
        "Spring Boot",
        "React",
      ],
      confidentiality: "Client work: the client, its data and internal details are left out on purpose.",
    },
  ],

  PULSE: {
    lede: "Real public activity, pulled from the GitHub API — how much I ship each quarter and the languages behind it. Web apps, backend services, games and developer tools each show a different part of my work.",
    takeaway: "I bring a systems view to product work: understand the domain, make the interface clear, and leave the codebase easier to extend.",
    note: `Generated from the GitHub API on ${GITHUB_STATS.generatedAt} by scripts/sync-github.mjs — the contribution calendar for volume, and commits attributed by each repository's primary language for the split. Private work counts toward the totals the way GitHub counts it; no private repository name is published.`,
    forHiringManagers: {
      title: "How I contribute",
      points: [
        { label: "Systems thinking", detail: "I connect domain decisions, async execution, persistence, and observability instead of treating them as separate layers." },
        {
          label: "Product awareness",
          detail: "I care about the interface around the system: clear workflows, useful feedback, and software people can keep using.",
        },
        {
          label: "Deliberate tooling",
          detail: "From CLIs to editor contributions, I look for small tools that remove friction from repeated work.",
        },
        { label: "Open collaboration", detail: "I am comfortable learning in public, receiving review, and making a contribution easy for someone else to pick up." },
      ],
    },
    kpis: [
      { label: "GitHub", value: GITHUB_STATS.lastYearContributions, hint: "Contributions, last 12 months" },
      { label: "Public repositories", value: GITHUB_STATS.publicRepos, hint: `${GITHUB_STATS.totalStars} stars across them` },
      { label: "At Luna S.r.l.", display: "Delivery → systems", hint: "Growing from shipped product to platform design" },
    ],
    phases: [
      { era: "’24", title: "University", body: "Vue and TypeScript. First multiplayer that friends sat down and played." },
      { era: "’25", title: "Internship", body: "Java and Spring in production. First Tokio service. A Zed grammar merged." },
      { era: "’26", title: "Systems work", body: "Rust services, a Java/React operator console, live telemetry, multiplayer games and developer tools." },
      { era: "Next", title: "Aiming at", body: "Kubernetes in production. Raft. An on-chain matcher." },
    ],
  },

  TOOLS: [
    { name: "OpenAI", product: "GPT 6 Sol", href: "https://openai.com", mark: "openai" },
    { name: "Zed", product: "IDE", href: "https://zed.dev", mark: "zed" },
    { name: "Delta", product: "Agent IDE", href: "https://delta.dev", mark: "delta" },
    { name: "Trama", product: "Workstreams", href: "https://trama.alessandrobrunoh.it", mark: "trama", mine: true },
  ],

  PRINCIPLES: [
    {
      tag: "Understand",
      title: "Find the real problem",
      body: "Before writing code, I understand who needs it, how they work and what a useful result looks like. The stack comes after the context.",
      detail: "I start with the people and the existing code: workflows, constraints, what already works and where it falls short. On client work that conversation is the job. We look at the options together, including what each one costs, and we pick one before I build it.",
      practice: [
        "Talk to the people who use or maintain the software.",
        "With a client, put the options and their cost on the table before choosing.",
        "Read the existing code and trace the affected workflow.",
        "Agree on the expected outcome, constraints and open questions.",
      ],
    },
    {
      tag: "Plan",
      title: "Write the problem down",
      body: "The problem becomes an issue in Trama before it becomes code. Then I decide what belongs in the change, what can wait, and how to know it works.",
      detail: "If it is not an issue, it is still a conversation. In Trama that issue is the record. When several issues share an outcome they become one workstream, with acceptance criteria you can check, not a pile of tickets. From there I break the solution into slices, make dependencies and trade-offs explicit, and choose tools that suit the codebase and the team.",
      practice: [
        "Open the issue in Trama before implementation.",
        "Group issues that share an outcome into one workstream, with criteria you can check.",
        "Split the work into small changes with a clear order, and decide how to test each step.",
      ],
    },
    {
      tag: "Build",
      title: "Turn intent into working software",
      body: "Connect the pieces, not just the layers: data, logic and interface. Build in small increments that can be run, tested and understood.",
      detail: "I choose the language and framework for the job: Rust for systems and tools, Java for backend applications, TypeScript and JavaScript for web and mobile, Python and SQL where they fit. The goal is a working slice with clear boundaries, not an impressive stack.",
      practice: [
        "Follow existing conventions and keep abstractions focused.",
        "Build an end-to-end slice before expanding the scope.",
        "Add tests, error handling and useful diagnostics alongside the feature.",
      ],
    },
    {
      tag: "Review",
      title: "Read it like someone else wrote it",
      body: "Question the implementation, test the edge cases and make each diff easy to review. Writing code is only part of the work; checking it matters just as much.",
      detail: "Recently I have started using Delta.dev to write code with AI agents, with a strong focus on review. I treat generated code as a proposal, not a finished result: I read the diff, check the design, run tests and ask for changes. The same discipline applies to code I write myself and to review with teammates.",
      practice: [
        "Read every diff for correctness, clarity and unintended changes.",
        "Run relevant tests and check failure paths, not only the happy path.",
        "Keep changes small and address review feedback before merging.",
      ],
    },
    {
      tag: "Share",
      title: "Leave context, not just code",
      body: "Explain what changed, why and how to verify it. A decision that should last goes on the workstream in Trama, not only in a chat.",
      detail: "Delta is where the implementation happens, including when an agent writes the code and I review it. The handoff should not depend on that thread. On the workstream in Trama I leave what someone still needs if they never open it: the decision, the pull request, what is still open. They can continue with their own editor and a normal Git workflow.",
      practice: [
        "Attach the pull request to the workstream, and record a decision there when someone who never opens Delta still needs it.",
        "Include reproducible checks next to the code.",
        "Make remaining questions explicit. Do not leave them only in an agent conversation.",
      ],
    },
  ],

  UI: {
    skipToContent: "Skip to content",
    tocIndex: "Index",
    tocCurrentWork: "Current work",
    tocLanguages: "Speaking",
    tocContact: "Contact",
    sectionTitles: {
      intro: "Intro",
      experience: "Experience",
      projects: "Projects",
      pulse: "Pulse",
      openSource: "Open Source",
      blog: "Blog",
      stack: "Stack",
      futureProjects: "Exploring",
      contact: "Contact",
      work: "Work",
      approach: "How I work",
    },
    close: "Close",
    toggleTheme: "Toggle color theme",
    openMenu: "Open menu",
    closeMenu: "Close menu",
    contactLede: "The fastest way to reach me is email — I read everything and reply.",
    emailLabel: "Email",
    copyEmail: "Copy address",
    copiedEmail: "Copied",
    readThesis: "Read the thesis",
  },
};
