import { GITHUB_STATS } from "./github-stats";
import type { SiteData } from "./site.types";

// Italian translation of site.en.ts — same shape, same ids/slugs/hrefs/keys,
// only human-readable copy is translated. Kept in sync by hand; if a field
// is added to site.en.ts, add its Italian counterpart here too.

export const IT: SiteData = {
  PROFILE: {
    name: "Alessandro Bruno",
    role: "Software Engineer — in produzione",
    shortRole: "Backend · Web & mobile · Tool per sviluppatori",
    headline: "Costruisco il software, e cosa costruire lo decido con chi lo deve usare.",
    location: "Bologna, Italia",
    github: "https://github.com/alessandrobrunoh",
    website: "https://alessandrobrunoh.it",
    email: "alessandro.brunoh@gmail.com",
    x: "",
    avatar: "/avatar.jpg",
    company: { name: "Luna S.r.l.", href: "https://lunapartner.it" },
    bio: "Sono un software engineer a Bologna. Mi incuriosisce capire come funziona davvero un sistema, e non mi piace lasciare un problema a metà. In Luna S.r.l. lavoro sul software dei clienti, quello già in produzione. Una parte importante del lavoro è sedersi con loro e decidere insieme cosa vale la pena costruire. Per conto mio faccio gli strumenti che mi mancavano. Trama è quello principale. Mi sono laureato all'Università di Bologna nel 2026, con una tesi sulla telemetria in tempo reale: PETRA.",
    availability: "Disponibile per ruoli da Software Engineer e Forward Deployed Engineer — backend, full-stack o a contatto con il cliente; da remoto o ibrido in Italia, con preavviso. Cittadino UE.",
  },

  TOC: [
    { n: "01", href: "#intro", label: "Intro" },
    { n: "02", href: "#experience", label: "Esperienza" },
    { n: "03", href: "#work", label: "Lavori" },
    { n: "04", href: "#approach", label: "Come lavoro" },
    { n: "05", href: "#contact", label: "Contatti" },
  ],

  COMPANY: {
    name: "Luna S.r.l.",
    href: "https://lunapartner.it",
    location: "Bologna, Italia",
    summary:
      "In Luna S.r.l. lavoro su diversi aspetti del software dei clienti: una piattaforma fleet con Java/Spring Boot, Angular e React Native, servizi in produzione in Rust e una nuova console operatore con API Spring Boot e interfaccia React. Prima di implementare discuto le opzioni con il cliente: cosa fare adesso, cosa può aspettare, e quanto costa ogni scelta a chi gestisce la piattaforma. Il codice passa da una code review senior.",
  },

  ROLES: [
    {
      title: "Sviluppatore Software",
      dates: "Giu 2026 — presente",
      current: true,
      caseId: "event-platform",
      bullets: [
        "Dentro la piattaforma in produzione di un cliente: servizi Rust event-driven che elaborano i suoi carichi — consumer asincroni su Valkey Streams, payload su S3.",
        "Ho reso i servizi osservabili da capo a capo: trace e log con OpenTelemetry verso Grafana, Loki e Tempo, così i problemi si seguono tra i servizi invece di indovinarli.",
        "Sto costruendo una nuova console operatore dall'inizio alla fine — API in Spring Boot e interfaccia React per chi gestisce la piattaforma ogni giorno.",
        "Le scelte di implementazione le discuto con il cliente prima di scriverle: cosa costruire, cosa lasciare, e cosa si rompe per chi opera la piattaforma se scegliamo male.",
      ],
      tags: ["Rust", "Tokio", "Valkey Streams", "S3", "OpenTelemetry", "Spring Boot", "React"],
    },
    {
      title: "Tirocinante Sviluppatore Software",
      dates: "Set 2025 — Giu 2026",
      current: false,
      bullets: [
        "Piattaforma fleet in Spring Boot, Angular e React Native, con aggiornamenti live via WebSocket.",
        "Dopo due mesi, passato al backend Rust in produzione di un cliente, rilasciando con code review senior.",
        "Diff piccoli e revisionabili su branch impilati — l'abitudine che rende sicuro portare modifiche nel sistema di qualcun altro.",
      ],
      tags: ["Spring Boot", "Angular", "React Native", "WebSocket", "Rust"],
    },
  ],

  EDUCATION: {
    school: "Università di Bologna — Campus di Cesena",
    degree: "Laurea in Tecnologie dei Sistemi Informatici",
    native: "B.Sc. Computer Systems Technologies",
    dates: "Laureato il 10 lug 2026",
    thesis:
      "Progettazione e Sviluppo di PETRA, una Piattaforma Event-Driven per la Telemetria e l'Analisi Asincrona in Tempo Reale",
    thesisHref: "",
  },

  CONTRIBUTIONS: [
    {
      status: "Published",
      title: "ducklake-orm",
      repo: "crates.io",
      href: "https://crates.io/crates/ducklake-orm",
      note: "ORM Rust con derive macro, query builder, pooling, migrazioni e time travel di DuckLake.",
    },
    {
      status: "Open",
      title: "UI per il port forwarding e forward SSH live",
      repo: "zed-industries/zed",
      href: "https://github.com/zed-industries/zed/pull/55248",
      note: "Aggiungere o rimuovere forward nelle sessioni remote senza riconnettersi.",
    },
    {
      status: "Merged",
      title: "Evidenziazione sintassi JDL",
      repo: "zed-industries/extensions",
      href: "https://github.com/zed-industries/extensions/pull/3339",
      note: "Una piccola estensione per l'editor.",
    },
  ],

  PROJECTS: [
    {
      id: "trama",
      name: "Trama",
      blurb: "Lo strato che manca tra un problema segnalato e una correzione rilasciata. Le issue restano. Un workstream porta l'esito, con decisioni e artefatti attaccati.",
      problem: "I tracker danno per scontato che un ticket sia una persona e una pull request. Non regge quando più bug hanno la stessa causa, il lavoro attraversa più repository e una parte la fa un agente. Il perché di una scelta finisce in una chat che un mese dopo non trova più nessuno.",
      decisions: [
        {
          title: "Tieni l'issue. Aggiungi il workstream.",
          context: "I team i ticket li conoscono già. Sostituirli il primo giorno è il modo più rapido per far ignorare uno strumento nuovo. Il ticket resta un buon modo per dire che qualcosa non va. È un cattivo modo per dire come un team, o un team e un agente, sistemerà più cose insieme.",
          choice: "L'issue resta l'unità di domanda, con una chiave tipo BUG-142. Il workstream è l'esito a cui ci si impegna, tipo AUTH-42, e può raccogliere le issue che condividono la causa. Lo stato viene dai fatti: criteri soddisfatti, pull request unite, domande ancora aperte. Si può comunque fissare a mano, quando serve.",
        },
        {
          title: "Non copiare la sessione di lavoro nel tracker",
          context: "L'implementazione vive già nell'editor, nel thread dell'agente e in Git. Una seconda copia invecchia, e costringe a riscrivere un lavoro già fatto.",
          choice: "Trama tiene quello che serve anche a chi quel thread non lo apre: l'obiettivo, chi ne risponde, la decisione, l'artefatto. La discussione resta dove è avvenuto il lavoro. Una decisione si promuove solo se deve sopravvivere alla sessione. Se una funzione sembra 'documenta di nuovo Delta', non ci entra.",
        },
        {
          title: "Niente progressi inventati",
          context: "Una percentuale sembra precisa e di solito non lo è. La telemetria di un agente e una barra 'fatto all'84%' sono contabilità, non un fatto che si può verificare.",
          choice: "Mostrare quello che si osserva: issue collegate e risolte, pull request aperte o unite, CI, una review in attesa. Suggerire un cambio di stato quando i fatti lo reggono. Non far finta che lo strumento sappia più di quanto ha misurato.",
        },
      ],
      href: "https://github.com/alessandrobrunoh/trama",
      stars: GITHUB_STATS.stars["trama"] ?? 0,
      lang: "TypeScript",
      meta: "Live",
      featured: true,
      year: "2026",
      demo: "https://trama.alessandrobrunoh.it",
      stack: ["Angular", "NestJS", "PostgreSQL", "Rust"],
      highlights: [
        "Le issue restano. Un workstream raggruppa quelle che condividono un esito",
        "Decisioni e artefatti, dalle pull request ai deploy, restano accanto a quell'esito",
        "Gli agenti sono membri. Una coda di attenzione mostra dove deve ancora decidere una persona",
        "Un Postgres e tre immagini piccole. Self-hosted, non una piattaforma da noleggiare",
      ],
      learned:
        "La parte difficile è stato il confine. Trama aiuta quando spiega l'esito, e dà fastidio nel momento in cui chiede di riscrivere un lavoro già fatto altrove.",
      body: "Trama è uno strato di coordinamento, con il sorgente disponibile, per team che rilasciano con persone e agenti. Il nome è la trama di un tessuto: il filo che attraversa il telaio e tiene insieme trefoli separati. Le issue restano il modo familiare di registrare un bug, una richiesta o una segnalazione. Il workstream è l'unità nuova, l'esito a cui un team si impegna, con criteri di accettazione, contributori e dipendenze. Le decisioni sono registri a sé, non un paragrafo perso in un thread. Gli artefatti sono la prova: pull request, build, report di test, deploy, con lo stato di CI e review. Un agente bloccato fa una domanda a una persona e aspetta, invece di indovinare. Persone e agenti sono entrambi attori, con token a scope stretto e una traccia. GitHub, GitLab e Bitbucket gli mandano pull request e webhook. Un server MCP in Rust, una novantina di tool, permette a un agente di leggere e modificare il workspace senza tenere dati propri. L'autorità resta l'API.",
    },
    {
      id: "eivar",
      name: "Eivar-Online",
      blurb: "Prototipo multiplayer: simulazione Rust server-authoritative, stato replicato, predizione lato client.",
      problem: "Come si mantiene coerente un mondo di gioco condiviso senza perdere reattività per ogni giocatore? Esploro simulazione autoritativa, stato replicato e predizione lato client in Rust.",
      href: "https://github.com/alessandrobrunoh/Eivar-Online",
      stars: GITHUB_STATS.stars["Eivar-Online"] ?? 0,
      lang: "Rust",
      meta: "In corso",
      featured: true,
      year: "2026",
      stack: ["Bevy", "SpacetimeDB", "WebAssembly", "Stato distribuito"],
      highlights: [
        "Simulazione server-authoritative con predizione lato client",
        "Stato replicato tramite un modulo SpacetimeDB compilato in WebAssembly",
        "Loot, raccolta, crafting e mercati tra giocatori come eventi di dominio delimitati",
      ],
      learned:
        "Come combinare ECS, stato replicato e predizione lato client: il server fa rispettare le regole, il client mantiene il gioco reattivo.",
      body: "Un prototipo multiplayer open source scritto in Rust, con Bevy ECS per il gameplay e SpacetimeDB per lo stato replicato. Lavoro su simulazione, predizione lato client e meccaniche di gioco: crowd-control, kit di abilità, loot, raccolta, crafting e mercati tra giocatori. Un progetto per esplorare insieme sviluppo di giochi, networking e WebAssembly.",
    },
    {
      id: "mnemosyne",
      name: "Mnemosyne",
      blurb: "Cronologia semantica del codice, local-first: simboli e modifiche strutturali via Tree-sitter, non diff per righe — interrogabile dagli agenti AI via MCP.",
      problem: "Git ricorda solo quello che committi. Tra un commit e l'altro il lavoro si perde, e i diff per righe non dicono quale funzione è cambiata né come. Volevo una cronologia locale che capisca la struttura del codice, interrogabile anche dagli strumenti AI.",
      href: "https://github.com/alessandrobrunoh/Mnemosyne",
      stars: GITHUB_STATS.stars["Mnemosyne"] ?? 0,
      lang: "Rust",
      meta: "Cronologia semantica",
      featured: true,
      year: "2026",
      stack: ["Tree-sitter", "redb", "Storage content-addressed", "MCP"],
      highlights: [
        "Traccia simboli e modifiche strutturali invece dei diff per righe",
        "Daemon, CLI e TUI sopra un workspace di storage content-addressed",
        "Accessibile agli strumenti AI tramite MCP",
      ],
      learned:
        "Rilasciare un demone che le persone usano davvero. Storage content-addressed, una TUI, e la disciplina di tenere ogni byte sul dispositivo.",
      body: "Lo strumento di cronologia locale che volevo usare ogni giorno. Un demone osserva i salvataggi, una TUI e una CLI cercano e ripristinano, e niente lascia la macchina. È ancora il progetto che mi ha insegnato a rilasciare uno strumento Rust che le persone usano davvero.",
    },
    {
      id: "ducklake",
      name: "ducklake-orm",
      blurb: "ORM Rust per DuckDB e DuckLake, pubblicato su crates.io — derive macro, query builder, pooling, migrazioni, time travel.",
      problem: "DuckDB e DuckLake sono ottimi per l'analisi, ma usarli da Rust significava SQL scritto a mano e risultati poco tipizzati. Volevo l'ergonomia di un ORM senza nascondere quello che il database fa bene.",
      decisions: [
        {
          title: "Errori tipizzati e default scopribili",
          context: "Lo storage analitico è potente, ma la potenza da sola non rende uno strumento piacevole da usare in una giornata normale.",
          choice: "Errori tipizzati, default che si scoprono dall'API e migrazioni dentro la libreria — così un nuovo utente può prevedere cosa succede senza aprire l'implementazione.",
        },
        {
          title: "Sapere dove si ferma l'astrazione",
          context: "Un ORM che nasconde tutto fa pagare a chi legge il prezzo della sua complessità.",
          choice: "Derive macro e query builder coprono il percorso comune — filtri, ordinamento, limit, count, fetch_one. Oltre, parla il database, compreso il time travel di DuckLake.",
        },
      ],
      href: "https://github.com/alessandrobrunoh/ducklake-orm",
      stars: GITHUB_STATS.stars["ducklake-orm"] ?? 0,
      lang: "Rust",
      meta: "crates.io",
      featured: true,
      year: "2026",
      stack: ["Rust", "DuckDB", "proc-macro", "SQL"],
      highlights: [
        "Le derive macro mappano struct in tabelle senza boilerplate",
        "Filtri type-safe, order_by, limit, count, fetch_one",
        "Pooling, migrazioni e time travel di DuckLake",
      ],
      learned: "Il livello sotto la query: confini tipizzati, ergonomia dei dati, e cosa serve per rendere lo storage analitico un prodotto.",
      body: "Un ORM Rust leggero per DuckDB, costruito per rendere lo storage analitico accessibile senza nasconderne le parti utili. Il lavoro riguarda confini tipizzati, ergonomia dei dati e piccole decisioni API che rendono uno strumento piacevole da continuare a usare.",
    },
    {
      id: "weaklings",
      name: "Weaklings-Manager",
      blurb: "Piattaforma self-hosted per gilde di Albion — banca, divisione del loot, analisi delle battaglie, login Discord.",
      problem: "Una gilda gestiva banca, divisione del loot ed eventi su fogli di calcolo e messaggi Discord. Serviva un unico strumento affidabile per gli ufficiali, con accessi legati ai ruoli che le persone avevano già su Discord.",
      href: "https://github.com/alessandrobrunoh/Weaklings-Manager",
      stars: GITHUB_STATS.stars["Weaklings-Manager"] ?? 0,
      lang: "Angular",
      meta: "API Axum",
      featured: false,
      year: "2026",
      stack: ["Axum", "PostgreSQL", "Angular", "Discord"],
      highlights: [
        "Banca di gilda e divisione del loot",
        "Sessioni evento con analisi delle battaglie",
        "Login Discord con accesso basato sui ruoli",
      ],
      learned:
        "Un dominio reale con utenti reali: autenticazione, banca, composizioni, e un bot che doveva restare online per una gilda — non una demo.",
      body: "Un'API Rust/Axum, una dashboard Angular e un bot Discord — che coprono banca, composizioni, tracciamento dell'energia sifonata e dati live di Albion. Costruito per una gilda che aveva bisogno di uno strumento vero, non di un foglio di calcolo.",
    },
    {
      id: "briscola",
      name: "Briscola Online",
      blurb: "Briscola in tempo reale via WebSocket. Multiplayer full-stack.",
      problem: "Un gruppo di amici voleva giocare a Briscola online, insieme e in tempo reale, a un tavolo che si comportasse come quello vero.",
      href: "https://github.com/alessandrobrunoh/Progetto-Ingegneria-Web",
      stars: GITHUB_STATS.stars["Progetto-Ingegneria-Web"] ?? 0,
      lang: "Vue",
      meta: "Web",
      featured: false,
      year: "2024",
      stack: ["Vue", "WebSocket", "Node"],
      highlights: ["Partite multiplayer dal vivo", "UI del tavolo responsive", "Dati di gioco persistenti"],
      learned:
        "La prima volta che un WebSocket doveva restare onesto per degli amici al tavolo — stato, turni, e un'interfaccia che poteva perdere.",
      body: "Progetto del corso di ingegneria del web che doveva davvero funzionare per giocare. Briscola in tempo reale via WebSocket, un frontend Vue, e abbastanza backend per mantenere onesta una partita. La prima volta che ho rilasciato qualcosa che degli amici si sono seduti a usare.",
    },
    {
      id: "sdp",
      name: "Semantic Delta Protocol",
      blurb: "Modifiche al codice a livello di AST — Tree-sitter e hashing strutturale.",
      problem: "I diff per righe perdono il codice quando si sposta o viene rinominato. Editor e strumenti devono seguire una funzione attraverso un refactor, non un numero di riga.",
      href: "https://github.com/alessandrobrunoh/Semantic-Delta-Protocol",
      lang: "Rust",
      meta: "Protocollo",
      featured: false,
      year: "2026",
      stack: ["Rust", "Tree-sitter", "JSON-RPC"],
      highlights: [
        "Simboli invece di diff per riga",
        "Hashing strutturale che sopravvive ai refactor",
        "Superficie JSON-RPC per gli editor",
      ],
      learned: "Un'identità che sopravvive a un rename. Tree-sitter percorre l'AST; gli hash mantengono una funzione la stessa funzione.",
      body: "Un protocollo per tracciare le modifiche a livello di funzione e classe, non di riga. Tree-sitter percorre l'AST; gli hash strutturali mantengono l'identità attraverso un rename. Il fratello di ricerca di Mnemosyne.",
    },
    {
      id: "vapt",
      name: "VAPT Research",
      blurb: "Report di sicurezza su un fork di OWASP Juice Shop.",
      problem: "Un corso di sicurezza chiedeva una vera valutazione, non un dump di scanner: trovare cosa è davvero sfruttabile in un'app volutamente vulnerabile e spiegare come correggerlo.",
      href: "https://github.com/alessandrobrunoh/Relazione-Sicurezza-Privacy",
      lang: "TypeScript",
      meta: "Ricerca",
      featured: false,
      year: "2025",
      stack: ["TypeScript", "OWASP", "VAPT"],
      highlights: [
        "Juice Shop forkato come bersaglio",
        "Risultati strutturati, non un dump di scansione",
        "Lavoro universitario che doveva leggersi come un report",
      ],
      learned: "Perimetro, exploit, impatto, correzione. Scrivere come un report, non come una classifica di CVE.",
      body: "Una valutazione delle vulnerabilità su un'app volutamente vulnerabile, scritta come un vero report. Il punto era il metodo: perimetro, exploit, impatto, correzione — non una classifica di CVE.",
    },
  ],

  STACK: {
    groups: [
      {
        name: "Rust",
        level: "Esperto",
        items: "Tokio · Axum · SQLx · Tree-sitter · Bevy",
        also: "Actix, SeaORM, Diesel, clap, ratatui, Leptos, Dioxus, GPUI, wasm-bindgen",
      },
      {
        name: "TypeScript",
        level: "Competente",
        items: "Angular · React · React Native · Node",
        also: "Svelte, Expo, NestJS, Tailwind CSS",
      },
      {
        name: "Java & Python",
        level: "Competente",
        items: "Spring Boot · Hibernate · Maven",
        also: "JHipster, Gradle, Kafka, Python",
      },
      {
        name: "Infrastruttura",
        level: "",
        items: "Docker · PostgreSQL · Valkey · S3 · OpenTelemetry · Grafana",
        also: "Linux, Loki, Tempo, Alloy, Redis, DuckLake, Kubernetes",
      },
    ],
  },

  FUTURE_PROJECTS: [
    {
      id: "solana-dex",
      name: "Mini DEX su Solana",
      blurb: "Matching degli ordini on-chain sotto i vincoli della blockchain.",
      href: "",
      lang: "Solana",
      meta: "Pianificato",
      year: "Prossimo",
      stack: ["Rust", "Solana", "Anchor"],
      highlights: [
        "Order book on-chain con logica di matching in un programma",
        "Vincoli del modello ad account invece di un database libero",
        "I limiti di compute budget costringono ogni istruzione a essere essenziale",
      ],
      learned: "Come regge il matching on-chain sotto il modello ad account di Solana e i limiti di calcolo — non solo la teoria.",
      body: "Un matcher di ordini per DEX scritto come programma Solana. La parte interessante non è la logica di matching — è costruirla dentro un modello ad account e un compute budget che ti costringono a giustificare ogni byte e ogni istruzione.",
    },
    {
      id: "btree-db",
      name: "Mini motore di database con un B-Tree",
      blurb: "Interni dello storage — il livello sotto gli ORM.",
      href: "https://github.com/alessandrobrunoh/mini-db-btree",
      lang: "Rust",
      meta: "Pianificato",
      year: "Prossimo",
      stack: ["Rust", "B-Tree", "Storage"],
      highlights: [
        "Split delle pagine, letture e scritture su pagine disco grezze",
        "Nessun ORM in mezzo — il livello di storage stesso",
        "Uno sguardo dalle fondamenta a ciò su cui poggia ducklake-orm",
      ],
      learned:
        "Cosa fa davvero un B-Tree su disco — split delle pagine, letture e scritture — invece di limitarsi a chiamarne uno tramite un ORM.",
      body: "Un piccolo motore di database costruito attorno a un B-Tree, da zero. Dopo aver pubblicato un ORM, questo è il livello sottostante: come i dati vengono davvero organizzati, suddivisi e trovati su disco.",
    },

  ],

  CASES: [
    {
      id: "event-platform",
      title: "Una piattaforma event-driven per un cliente",
      role: "Sviluppatore Software · Luna S.r.l.",
      era: "2025 — oggi",
      blurb: "Lavoro dentro il backend in produzione di un cliente: consumer Rust su Valkey Streams, payload su S3, tracing da capo a capo e una console operatore per chi gestisce la piattaforma.",
      problem: "Un cliente fa girare i suoi carichi su un backend event-driven. Il lavoro arriva come eventi, i payload stanno su S3, e ogni evento deve produrre il suo effetto una volta sola — sotto carico, con i retry — mentre chi gestisce la piattaforma deve poter vedere cosa è successo quando qualcosa va storto.",
      built: [
        "Consumer asincroni in Rust su Valkey Streams che leggono, elaborano e confermano gli eventi, con i payload su S3.",
        "Tracing e logging con OpenTelemetry verso Grafana, Loki e Tempo, così un singolo evento si può seguire tra i servizi.",
        "Una nuova console operatore — API in Spring Boot e interfaccia React — per chi gestisce la piattaforma ogni giorno.",
        "Tutto rilasciato in diff piccoli e revisionabili, con code review senior.",
      ],
      decisions: [
        {
          title: "Confermare dopo l'effetto, non dopo la lettura",
          context: "Venivo da un mondo request/response, dove una chiamata riceve risposta e si dimentica. Su un event bus trattavo “consegnato” ed “elaborato” come la stessa cosa. Non lo sono: lo spazio tra i due è dove vivono retry, duplicati e problemi di ordinamento.",
          choice: "Rendere ogni consumer una piccola macchina a stati esplicita — leggi, elabora, conferma — e confermare solo quando il lavoro è stato davvero fatto. I retry hanno smesso di essere casi limite e sono diventati parte del design.",
          code: "// delivered is not processed\nlet message = stream.read().await?;\nif worker.handle(&message).await? {\n    stream.ack(message.id).await?;\n}",
        },
        {
          title: "Prima l'osservabilità, poi la fiducia",
          context: "Un event bus fallisce in silenzio: un messaggio mai elaborato può sembrare identico a uno elaborato.",
          choice: "Trace e log con OpenTelemetry, verso Grafana, Loki e Tempo, prima di costruire altro sopra il bus — così ogni evento si segue da capo a capo e i problemi si trovano dalle prove, non dalle ipotesi.",
        },
        {
          title: "Scegliere con il cliente, non dopo",
          context: "Questo è il sistema in produzione di qualcun altro. Un design che a me sembra pulito e a chi lo gestisce sembra sbagliato non è un buon design, e il costo di una scelta io non lo vedo bene come lo vedono loro.",
          choice: "Metto le opzioni sul tavolo con loro: cosa fare adesso, cosa può aspettare, e cosa si rompe se indoviniamo. Ne scegliamo una, poi la scrivo. Le decisioni tecniche qui sopra sono uscite da quelle conversazioni, non da un ticket lanciato oltre un muro.",
        },
      ],
      learned: "Consegnare non è elaborare. Quando le transizioni sono esplicite e osservabili, un sistema event-driven diventa qualcosa su cui si può ragionare, e che si può spiegare a chi ci fa affidamento. Lo stesso vale per le scelte: si difendono meglio se il cliente era nella stanza quando le abbiamo prese.",
      stack: [
        "Rust",
        "Tokio",
        "Valkey Streams",
        "S3",
        "OpenTelemetry",
        "Grafana",
        "Loki",
        "Tempo",
        "Spring Boot",
        "React",
      ],
      confidentiality: "Lavoro per un cliente: il cliente, i suoi dati e i dettagli interni sono omessi di proposito.",
    },
  ],

  PULSE: {
    lede: "Attività pubblica reale, presa dall'API di GitHub — quanto rilascio ogni trimestre e con quali linguaggi. Applicazioni web, backend, giochi e strumenti per sviluppatori raccontano aspetti diversi del mio lavoro.",
    takeaway: "Porto una visione sistemica nel lavoro di prodotto: capire il dominio, rendere chiara l'interfaccia e lasciare una codebase più facile da estendere.",
    note: `Generato dall'API di GitHub il ${GITHUB_STATS.generatedAt} da scripts/sync-github.mjs — il calendario dei contributi per il volume, e i commit attribuiti al linguaggio principale di ogni repository per la ripartizione. Il lavoro privato conta nei totali come lo conta GitHub; nessun nome di repository privato viene pubblicato.`,
    forHiringManagers: {
      title: "Come contribuisco",
      points: [
        { label: "Pensiero sistemico", detail: "Collego dominio, asincronia, persistenza e osservabilità senza trattarli come livelli isolati." },
        {
          label: "Consapevolezza del prodotto",
          detail: "Mi interessa l'interfaccia attorno al sistema: flussi chiari, feedback utili e software che si possa continuare a usare.",
        },
        {
          label: "Tooling deliberato",
          detail: "Dalle CLI ai contributi agli editor, cerco strumenti piccoli che eliminino attrito dal lavoro ripetuto.",
        },
        { label: "Collaborazione aperta", detail: "Imparo volentieri in pubblico, ricevo review e rendo i contributi facili da riprendere per altri." },
      ],
    },
    kpis: [
      { label: "GitHub", value: GITHUB_STATS.lastYearContributions, hint: "Contributi, ultimi 12 mesi" },
      { label: "Repository pubblici", value: GITHUB_STATS.publicRepos, hint: `${GITHUB_STATS.totalStars} stelle in totale` },
      { label: "In Luna S.r.l.", display: "Delivery → sistemi", hint: "Dal prodotto rilasciato alla progettazione della piattaforma" },
    ],
    phases: [
      { era: "’24", title: "Università", body: "Vue e TypeScript. Il primo multiplayer a cui gli amici si sono seduti a giocare." },
      { era: "’25", title: "Tirocinio", body: "Java e Spring in produzione. Primo servizio Tokio. Una grammatica per Zed unita." },
      { era: "’26", title: "Lavoro sui sistemi", body: "Servizi Rust, una console operatore Java/React, telemetria live, giochi multiplayer e strumenti per sviluppatori." },
      { era: "Prossimo", title: "Prossimo obiettivo", body: "Kubernetes in produzione. Raft. Un matcher on-chain." },
    ],
  },

  TOOLS: [
    { name: "OpenAI", product: "GPT 6 Sol", href: "https://openai.com", mark: "openai" },
    { name: "Zed", product: "IDE", href: "https://zed.dev", mark: "zed" },
    { name: "Delta", product: "IDE Agente", href: "https://delta.dev", mark: "delta" },
    { name: "Trama", product: "Workstream", href: "https://trama.alessandrobrunoh.it", mark: "trama", mine: true },
  ],

  PRINCIPLES: [
    {
      tag: "Capire",
      title: "Trovo il problema reale",
      body: "Prima del codice, capisco a chi serve, come lavora e cosa rende utile il risultato. Lo stack viene dopo il contesto.",
      detail: "Parto dalle persone e dal codice esistente: flussi, vincoli, cosa funziona già e cosa manca. Sul lavoro per un cliente quella conversazione è il lavoro. Guardiamo le opzioni insieme, compreso quanto costa ciascuna, e ne scegliamo una prima che io la costruisca.",
      practice: [
        "Parlo con chi usa o mantiene il software.",
        "Con un cliente, metto sul tavolo le opzioni e il loro costo prima di scegliere.",
        "Leggo il codice esistente e seguo il flusso interessato dalla modifica.",
        "Chiarisco risultato atteso, vincoli e domande ancora aperte.",
      ],
    },
    {
      tag: "Pianificare",
      title: "Scrivo il problema",
      body: "Il problema diventa un'issue in Trama prima di diventare codice. Poi decido cosa rientra nella modifica, cosa può aspettare e come capire se funziona.",
      detail: "Se non è un'issue, è ancora una conversazione. In Trama quell'issue è il registro. Quando più issue condividono un esito diventano un workstream, con criteri di accettazione verificabili, non un mucchio di ticket. Da lì divido la soluzione in incrementi, esplicito dipendenze e compromessi e scelgo strumenti adatti alla codebase e al team.",
      practice: [
        "Apro l'issue in Trama prima di implementare.",
        "Raggruppo in un workstream le issue che condividono un esito, con criteri che si possono verificare.",
        "Divido il lavoro in modifiche piccole con un ordine chiaro, e decido come verificare ogni passo.",
      ],
    },
    {
      tag: "Costruire",
      title: "Dall’idea al software che funziona",
      body: "Collego i pezzi, non solo i livelli: dati, logica e interfaccia. Costruisco per piccoli incrementi che si possono eseguire, testare e capire.",
      detail: "Scelgo linguaggio e framework in base al lavoro: Rust per sistemi e tool, Java per applicazioni backend, TypeScript e JavaScript per web e mobile, Python e SQL dove servono. L’obiettivo è una funzionalità completa con confini chiari, non uno stack da esibire.",
      practice: [
        "Seguo le convenzioni esistenti e mantengo le astrazioni mirate.",
        "Costruisco un primo percorso completo prima di allargare il perimetro.",
        "Aggiungo test, gestione degli errori e diagnostica insieme alla funzionalità.",
      ],
    },
    {
      tag: "Review",
      title: "Lo rileggo come se non fosse mio",
      body: "Metto in discussione l’implementazione, verifico i casi limite e rendo ogni diff facile da rivedere. Scrivere codice è solo una parte del lavoro: controllarlo conta altrettanto.",
      detail: "Recentemente ho iniziato a usare Delta.dev per scrivere codice con agenti AI, dedicando molta attenzione alla review. Considero il codice generato una proposta, non un risultato finito: leggo il diff, verifico il design, eseguo i test e chiedo correzioni. La stessa disciplina vale per il codice che scrivo io e per le review con il team.",
      practice: [
        "Leggo ogni diff cercando correttezza, chiarezza e modifiche involontarie.",
        "Eseguo i test pertinenti e verifico anche i percorsi di errore.",
        "Mantengo le modifiche piccole e risolvo il feedback prima del merge.",
      ],
    },
    {
      tag: "Condividere",
      title: "Lascio contesto, non solo codice",
      body: "Spiego cosa è cambiato, perché e come verificarlo. Una decisione che deve durare va sul workstream in Trama, non solo in una chat.",
      detail: "Delta è dove avviene l'implementazione, anche quando il codice lo scrive un agente e io lo revisiono. Il passaggio di consegne non deve dipendere da quel thread. Sul workstream in Trama lascio quello che serve a chi non lo apre: la decisione, la pull request, cosa è ancora aperto. Si può continuare con il proprio editor e un normale workflow Git.",
      practice: [
        "Attacco la pull request al workstream, e ci registro una decisione quando serve a chi Delta non lo apre.",
        "Includo verifiche riproducibili accanto al codice.",
        "Esplicito le domande aperte. Non le lascio solo in una conversazione con un agente.",
      ],
    },
  ],

  UI: {
    skipToContent: "Vai al contenuto",
    tocIndex: "Indice",
    tocCurrentWork: "Lavoro attuale",
    tocLanguages: "Lingue parlate",
    tocContact: "Contatti",
    sectionTitles: {
      intro: "Intro",
      experience: "Esperienza",
      projects: "Progetti",
      pulse: "Attività",
      openSource: "Open Source",
      blog: "Blog",
      stack: "Stack",
      futureProjects: "Esplorazioni",
      contact: "Contatti",
      work: "Lavori",
      approach: "Come lavoro",
    },
    close: "Chiudi",
    toggleTheme: "Cambia tema colore",
    openMenu: "Apri il menu",
    closeMenu: "Chiudi il menu",
    contactLede: "Il modo più veloce per raggiungermi è l'email — leggo tutto e rispondo.",
    emailLabel: "Email",
    copyEmail: "Copia indirizzo",
    copiedEmail: "Copiato",
    readThesis: "Leggi la tesi",
  },
};
