import { GITHUB_STATS } from "./github-stats";
import type { SiteData } from "./site.types";

// Italian translation of site.en.ts — same shape, same ids/slugs/hrefs/keys,
// only human-readable copy is translated. Kept in sync by hand; if a field
// is added to site.en.ts, add its Italian counterpart here too.

export const IT: SiteData = {
  PROFILE: {
    name: "Alessandro Bruno",
    role: "Software Engineer — Systems & Product",
    shortRole: "Backend · Web & mobile · Tool per sviluppatori",
    headline: "Costruisco software in produzione dall'inizio alla fine, vicino a chi lo usa.",
    location: "Bologna, Italia",
    github: "https://github.com/alessandrobrunoh",
    website: "https://alessandrobrunoh.it",
    email: "alessandro.brunoh@gmail.com",
    x: "",
    avatar: "/avatar.jpg",
    company: { name: "Luna S.r.l.", href: "https://lunapartner.it" },
    bio: "Software engineer a Bologna: lavoro su backend, interfacce web e mobile, database e strumenti per sviluppatori. Uso Rust, Java, TypeScript, JavaScript, Python e SQL, scegliendo il linguaggio in base al problema invece di adattare ogni progetto allo stesso stack. In Luna S.r.l. ho lavorato su software fleet con Spring Boot, Angular e React Native, servizi Rust in produzione e una console operatore con Spring Boot e React — sempre con code review senior. I miei progetti spaziano dai giochi multiplayer con Bevy e Vue a ducklake-orm, un ORM pubblicato su crates.io, e Mnemosyne, uno strumento local-first per la cronologia del codice basato su Tree-sitter. La mia tesi triennale, PETRA, esplora telemetria e analisi in tempo reale; il lavoro universitario sulla sicurezza riguarda valutazione delle vulnerabilità e correzioni.",
    availability: "Disponibile per ruoli da Software Engineer e Forward Deployed Engineer — backend, full-stack o a contatto con il cliente; da remoto o ibrido in Italia, con preavviso. Cittadino UE.",
  },

  TOC: [
    { n: "01", href: "#intro", label: "Intro" },
    { n: "02", href: "#experience", label: "Esperienza" },
    { n: "03", href: "#work", label: "Lavori" },
    { n: "04", href: "#approach", label: "Come lavoro" },
    { n: "05", href: "#contact", label: "Contatti" },
  ],

  COMPANY: {
    name: "Luna S.r.l.",
    href: "https://lunapartner.it",
    location: "Bologna, Italia",
    summary:
      "In Luna S.r.l. lavoro su diversi aspetti del software dei clienti: una piattaforma fleet con Java/Spring Boot, Angular e React Native, servizi in produzione in Rust e una nuova console operatore con API Spring Boot e interfaccia React. Mi occupo di logica applicativa, dati, interfacce e osservabilità, con code review senior.",
  },

  ROLES: [
    {
      title: "Sviluppatore Software",
      dates: "Giu 2026 — presente",
      current: true,
      caseId: "event-platform",
      bullets: [
        "Dentro la piattaforma in produzione di un cliente: servizi Rust event-driven che elaborano i suoi carichi — consumer asincroni su Valkey Streams, payload su S3.",
        "Ho reso i servizi osservabili da capo a capo: trace e log con OpenTelemetry verso Grafana, Loki e Tempo, così i problemi si seguono tra i servizi invece di indovinarli.",
        "Sto costruendo una nuova console operatore dall'inizio alla fine — API in Spring Boot e interfaccia React per chi gestisce la piattaforma ogni giorno.",
      ],
      tags: ["Rust", "Tokio", "Valkey Streams", "S3", "OpenTelemetry", "Spring Boot", "React"],
    },
    {
      title: "Tirocinante Sviluppatore Software",
      dates: "Set 2025 — Giu 2026",
      current: false,
      bullets: [
        "Piattaforma fleet in Spring Boot, Angular e React Native, con aggiornamenti live via WebSocket.",
        "Dopo due mesi, passato al backend Rust in produzione di un cliente, rilasciando con code review senior.",
        "Diff piccoli e revisionabili su branch impilati — l'abitudine che rende sicuro portare modifiche nel sistema di qualcun altro.",
      ],
      tags: ["Spring Boot", "Angular", "React Native", "WebSocket", "Rust"],
    },
  ],

  EDUCATION: {
    school: "Università di Bologna — Campus di Cesena",
    degree: "Laurea in Tecnologie dei Sistemi Informatici",
    native: "B.Sc. Computer Systems Technologies",
    dates: "Laureato il 10 lug 2026",
    thesis:
      "Progettazione e Sviluppo di PETRA, una Piattaforma Event-Driven per la Telemetria e l'Analisi Asincrona in Tempo Reale",
    thesisHref: "",
  },

  CONTRIBUTIONS: [
    {
      status: "Published",
      title: "ducklake-orm",
      repo: "crates.io",
      href: "https://crates.io/crates/ducklake-orm",
      note: "ORM Rust con derive macro, query builder, pooling, migrazioni e time travel di DuckLake.",
    },
    {
      status: "Open",
      title: "UI per il port forwarding e forward SSH live",
      repo: "zed-industries/zed",
      href: "https://github.com/zed-industries/zed/pull/55248",
      note: "Aggiungere o rimuovere forward nelle sessioni remote senza riconnettersi.",
    },
    {
      status: "Merged",
      title: "Evidenziazione sintassi JDL",
      repo: "zed-industries/extensions",
      href: "https://github.com/zed-industries/extensions/pull/3339",
      note: "Una piccola estensione per l'editor.",
    },
  ],

  PROJECTS: [
    {
      id: "eivar",
      name: "Eivar-Online",
      blurb: "Prototipo multiplayer: simulazione Rust server-authoritative, stato replicato, predizione lato client.",
      problem: "Come si mantiene coerente un mondo di gioco condiviso senza perdere reattività per ogni giocatore? Esploro simulazione autoritativa, stato replicato e predizione lato client in Rust.",
      href: "https://github.com/alessandrobrunoh/Eivar-Online",
      stars: GITHUB_STATS.stars["Eivar-Online"] ?? 0,
      lang: "Rust",
      meta: "In corso",
      featured: true,
      year: "2026",
      stack: ["Bevy", "SpacetimeDB", "WebAssembly", "Stato distribuito"],
      highlights: [
        "Simulazione server-authoritative con predizione lato client",
        "Stato replicato tramite un modulo SpacetimeDB compilato in WebAssembly",
        "Loot, raccolta, crafting e mercati tra giocatori come eventi di dominio delimitati",
      ],
      learned:
        "Come combinare ECS, stato replicato e predizione lato client: il server fa rispettare le regole, il client mantiene il gioco reattivo.",
      body: "Un prototipo multiplayer open source scritto in Rust, con Bevy ECS per il gameplay e SpacetimeDB per lo stato replicato. Lavoro su simulazione, predizione lato client e meccaniche di gioco: crowd-control, kit di abilità, loot, raccolta, crafting e mercati tra giocatori. Un progetto per esplorare insieme sviluppo di giochi, networking e WebAssembly.",
    },
    {
      id: "mnemosyne",
      name: "Mnemosyne",
      blurb: "Cronologia semantica del codice, local-first: simboli e modifiche strutturali via Tree-sitter, non diff per righe — interrogabile dagli agenti AI via MCP.",
      problem: "Git ricorda solo quello che committi. Tra un commit e l'altro il lavoro si perde, e i diff per righe non dicono quale funzione è cambiata né come. Volevo una cronologia locale che capisca la struttura del codice, interrogabile anche dagli strumenti AI.",
      href: "https://github.com/alessandrobrunoh/Mnemosyne",
      stars: GITHUB_STATS.stars["Mnemosyne"] ?? 0,
      lang: "Rust",
      meta: "Cronologia semantica",
      featured: true,
      year: "2026",
      stack: ["Tree-sitter", "redb", "Storage content-addressed", "MCP"],
      highlights: [
        "Traccia simboli e modifiche strutturali invece dei diff per righe",
        "Daemon, CLI e TUI sopra un workspace di storage content-addressed",
        "Accessibile agli strumenti AI tramite MCP",
      ],
      learned:
        "Rilasciare un demone che le persone usano davvero. Storage content-addressed, una TUI, e la disciplina di tenere ogni byte sul dispositivo.",
      body: "Lo strumento di cronologia locale che volevo usare ogni giorno. Un demone osserva i salvataggi, una TUI e una CLI cercano e ripristinano, e niente lascia la macchina. È ancora il progetto che mi ha insegnato a rilasciare uno strumento Rust che le persone usano davvero.",
    },
    {
      id: "ducklake",
      name: "ducklake-orm",
      blurb: "ORM Rust per DuckDB e DuckLake, pubblicato su crates.io — derive macro, query builder, pooling, migrazioni, time travel.",
      problem: "DuckDB e DuckLake sono ottimi per l'analisi, ma usarli da Rust significava SQL scritto a mano e risultati poco tipizzati. Volevo l'ergonomia di un ORM senza nascondere quello che il database fa bene.",
      decisions: [
        {
          title: "Errori tipizzati e default scopribili",
          context: "Lo storage analitico è potente, ma la potenza da sola non rende uno strumento piacevole da usare in una giornata normale.",
          choice: "Errori tipizzati, default che si scoprono dall'API e migrazioni dentro la libreria — così un nuovo utente può prevedere cosa succede senza aprire l'implementazione.",
        },
        {
          title: "Sapere dove si ferma l'astrazione",
          context: "Un ORM che nasconde tutto fa pagare a chi legge il prezzo della sua complessità.",
          choice: "Derive macro e query builder coprono il percorso comune — filtri, ordinamento, limit, count, fetch_one. Oltre, parla il database, compreso il time travel di DuckLake.",
        },
      ],
      href: "https://github.com/alessandrobrunoh/ducklake-orm",
      stars: GITHUB_STATS.stars["ducklake-orm"] ?? 0,
      lang: "Rust",
      meta: "crates.io",
      featured: true,
      year: "2026",
      stack: ["Rust", "DuckDB", "proc-macro", "SQL"],
      highlights: [
        "Le derive macro mappano struct in tabelle senza boilerplate",
        "Filtri type-safe, order_by, limit, count, fetch_one",
        "Pooling, migrazioni e time travel di DuckLake",
      ],
      learned: "Il livello sotto la query: confini tipizzati, ergonomia dei dati, e cosa serve per rendere lo storage analitico un prodotto.",
      body: "Un ORM Rust leggero per DuckDB, costruito per rendere lo storage analitico accessibile senza nasconderne le parti utili. Il lavoro riguarda confini tipizzati, ergonomia dei dati e piccole decisioni API che rendono uno strumento piacevole da continuare a usare.",
    },
    {
      id: "weaklings",
      name: "Weaklings-Manager",
      blurb: "Piattaforma self-hosted per gilde di Albion — banca, divisione del loot, analisi delle battaglie, login Discord.",
      problem: "Una gilda gestiva banca, divisione del loot ed eventi su fogli di calcolo e messaggi Discord. Serviva un unico strumento affidabile per gli ufficiali, con accessi legati ai ruoli che le persone avevano già su Discord.",
      href: "https://github.com/alessandrobrunoh/Weaklings-Manager",
      stars: GITHUB_STATS.stars["Weaklings-Manager"] ?? 0,
      lang: "Angular",
      meta: "API Axum",
      featured: false,
      year: "2026",
      stack: ["Axum", "PostgreSQL", "Angular", "Discord"],
      highlights: [
        "Banca di gilda e divisione del loot",
        "Sessioni evento con analisi delle battaglie",
        "Login Discord con accesso basato sui ruoli",
      ],
      learned:
        "Un dominio reale con utenti reali: autenticazione, banca, composizioni, e un bot che doveva restare online per una gilda — non una demo.",
      body: "Un'API Rust/Axum, una dashboard Angular e un bot Discord — che coprono banca, composizioni, tracciamento dell'energia sifonata e dati live di Albion. Costruito per una gilda che aveva bisogno di uno strumento vero, non di un foglio di calcolo.",
    },
    {
      id: "ketchapp",
      name: "KetchApp",
      blurb: "Produttività nello studio come microservizi. Pomodoro, piani con IA, notifiche asincrone.",
      problem: "Un team universitario aveva bisogno di un'app di studio con sessioni Pomodoro, piani generati dall'AI e notifiche — costruita da più persone insieme senza pestarsi i piedi.",
      href: "https://github.com/orgs/ketchapp-for-study",
      lang: "Java",
      meta: "Org",
      featured: false,
      year: "2025",
      stack: ["Rust", "Java", "Kafka", "Auth"],
      highlights: ["API di autenticazione in Rust", "Notifiche basate su Kafka", "Servizi separati invece di un monolite"],
      learned:
        "Dove si rompe un monolite. Autenticazione in Rust, notifiche su Kafka, e le giunture che si vedono solo quando i pezzi iniziano a muoversi.",
      body: "Progetto universitario di gruppo diventato il mio primo vero taglio a microservizi: un'API di autenticazione in Rust, un percorso Java su Kafka, e notifiche asincrone per Pomodoro e piani di studio. L'organizzazione mantiene ancora questa suddivisione.",
    },
    {
      id: "briscola",
      name: "Briscola Online",
      blurb: "Briscola in tempo reale via WebSocket. Multiplayer full-stack.",
      problem: "Un gruppo di amici voleva giocare a Briscola online, insieme e in tempo reale, a un tavolo che si comportasse come quello vero.",
      href: "https://github.com/alessandrobrunoh/Progetto-Ingegneria-Web",
      stars: GITHUB_STATS.stars["Progetto-Ingegneria-Web"] ?? 0,
      lang: "Vue",
      meta: "Web",
      featured: false,
      year: "2024",
      stack: ["Vue", "WebSocket", "Node"],
      highlights: ["Partite multiplayer dal vivo", "UI del tavolo responsive", "Dati di gioco persistenti"],
      learned:
        "La prima volta che un WebSocket doveva restare onesto per degli amici al tavolo — stato, turni, e un'interfaccia che poteva perdere.",
      body: "Progetto del corso di ingegneria del web che doveva davvero funzionare per giocare. Briscola in tempo reale via WebSocket, un frontend Vue, e abbastanza backend per mantenere onesta una partita. La prima volta che ho rilasciato qualcosa che degli amici si sono seduti a usare.",
    },
    {
      id: "sdp",
      name: "Semantic Delta Protocol",
      blurb: "Modifiche al codice a livello di AST — Tree-sitter e hashing strutturale.",
      problem: "I diff per righe perdono il codice quando si sposta o viene rinominato. Editor e strumenti devono seguire una funzione attraverso un refactor, non un numero di riga.",
      href: "https://github.com/alessandrobrunoh/Semantic-Delta-Protocol",
      lang: "Rust",
      meta: "Protocollo",
      featured: false,
      year: "2026",
      stack: ["Rust", "Tree-sitter", "JSON-RPC"],
      highlights: [
        "Simboli invece di diff per riga",
        "Hashing strutturale che sopravvive ai refactor",
        "Superficie JSON-RPC per gli editor",
      ],
      learned: "Un'identità che sopravvive a un rename. Tree-sitter percorre l'AST; gli hash mantengono una funzione la stessa funzione.",
      body: "Un protocollo per tracciare le modifiche a livello di funzione e classe, non di riga. Tree-sitter percorre l'AST; gli hash strutturali mantengono l'identità attraverso un rename. Il fratello di ricerca di Mnemosyne.",
    },
    {
      id: "vapt",
      name: "VAPT Research",
      blurb: "Report di sicurezza su un fork di OWASP Juice Shop.",
      problem: "Un corso di sicurezza chiedeva una vera valutazione, non un dump di scanner: trovare cosa è davvero sfruttabile in un'app volutamente vulnerabile e spiegare come correggerlo.",
      href: "https://github.com/alessandrobrunoh/Relazione-Sicurezza-Privacy",
      lang: "TypeScript",
      meta: "Ricerca",
      featured: false,
      year: "2025",
      stack: ["TypeScript", "OWASP", "VAPT"],
      highlights: [
        "Juice Shop forkato come bersaglio",
        "Risultati strutturati, non un dump di scansione",
        "Lavoro universitario che doveva leggersi come un report",
      ],
      learned: "Perimetro, exploit, impatto, correzione. Scrivere come un report, non come una classifica di CVE.",
      body: "Una valutazione delle vulnerabilità su un'app volutamente vulnerabile, scritta come un vero report. Il punto era il metodo: perimetro, exploit, impatto, correzione — non una classifica di CVE.",
    },
  ],

  STACK: {
    groups: [
      {
        name: "Rust",
        level: "Esperto",
        items: "Tokio · Axum · SQLx · Tree-sitter · Bevy",
        also: "Actix, SeaORM, Diesel, clap, ratatui, Leptos, Dioxus, GPUI, wasm-bindgen",
      },
      {
        name: "TypeScript",
        level: "Competente",
        items: "Angular · React · React Native · Node",
        also: "Svelte, Expo, NestJS, Tailwind CSS",
      },
      {
        name: "Java & Python",
        level: "Competente",
        items: "Spring Boot · Hibernate · Maven",
        also: "JHipster, Gradle, Kafka, Python",
      },
      {
        name: "Infrastruttura",
        level: "",
        items: "Docker · PostgreSQL · Valkey · S3 · OpenTelemetry · Grafana",
        also: "Linux, Loki, Tempo, Alloy, Redis, DuckLake, Kubernetes",
      },
    ],
  },

  FUTURE_PROJECTS: [
    {
      id: "solana-dex",
      name: "Mini DEX su Solana",
      blurb: "Matching degli ordini on-chain sotto i vincoli della blockchain.",
      href: "",
      lang: "Solana",
      meta: "Pianificato",
      year: "Prossimo",
      stack: ["Rust", "Solana", "Anchor"],
      highlights: [
        "Order book on-chain con logica di matching in un programma",
        "Vincoli del modello ad account invece di un database libero",
        "I limiti di compute budget costringono ogni istruzione a essere essenziale",
      ],
      learned: "Come regge il matching on-chain sotto il modello ad account di Solana e i limiti di calcolo — non solo la teoria.",
      body: "Un matcher di ordini per DEX scritto come programma Solana. La parte interessante non è la logica di matching — è costruirla dentro un modello ad account e un compute budget che ti costringono a giustificare ogni byte e ogni istruzione.",
    },
    {
      id: "btree-db",
      name: "Mini motore di database con un B-Tree",
      blurb: "Interni dello storage — il livello sotto gli ORM.",
      href: "https://github.com/alessandrobrunoh/mini-db-btree",
      lang: "Rust",
      meta: "Pianificato",
      year: "Prossimo",
      stack: ["Rust", "B-Tree", "Storage"],
      highlights: [
        "Split delle pagine, letture e scritture su pagine disco grezze",
        "Nessun ORM in mezzo — il livello di storage stesso",
        "Uno sguardo dalle fondamenta a ciò su cui poggia ducklake-orm",
      ],
      learned:
        "Cosa fa davvero un B-Tree su disco — split delle pagine, letture e scritture — invece di limitarsi a chiamarne uno tramite un ORM.",
      body: "Un piccolo motore di database costruito attorno a un B-Tree, da zero. Dopo aver pubblicato un ORM, questo è il livello sottostante: come i dati vengono davvero organizzati, suddivisi e trovati su disco.",
    },

  ],

  CASES: [
    {
      id: "event-platform",
      title: "Una piattaforma event-driven per un cliente",
      role: "Sviluppatore Software · Luna S.r.l.",
      era: "2025 — oggi",
      blurb: "Lavoro dentro il backend in produzione di un cliente: consumer Rust su Valkey Streams, payload su S3, tracing da capo a capo e una console operatore per chi gestisce la piattaforma.",
      problem: "Un cliente fa girare i suoi carichi su un backend event-driven. Il lavoro arriva come eventi, i payload stanno su S3, e ogni evento deve produrre il suo effetto una volta sola — sotto carico, con i retry — mentre chi gestisce la piattaforma deve poter vedere cosa è successo quando qualcosa va storto.",
      built: [
        "Consumer asincroni in Rust su Valkey Streams che leggono, elaborano e confermano gli eventi, con i payload su S3.",
        "Tracing e logging con OpenTelemetry verso Grafana, Loki e Tempo, così un singolo evento si può seguire tra i servizi.",
        "Una nuova console operatore — API in Spring Boot e interfaccia React — per chi gestisce la piattaforma ogni giorno.",
        "Tutto rilasciato in diff piccoli e revisionabili, con code review senior.",
      ],
      decisions: [
        {
          title: "Confermare dopo l'effetto, non dopo la lettura",
          context: "Venivo da un mondo request/response, dove una chiamata riceve risposta e si dimentica. Su un event bus trattavo “consegnato” ed “elaborato” come la stessa cosa. Non lo sono: lo spazio tra i due è dove vivono retry, duplicati e problemi di ordinamento.",
          choice: "Rendere ogni consumer una piccola macchina a stati esplicita — leggi, elabora, conferma — e confermare solo quando il lavoro è stato davvero fatto. I retry hanno smesso di essere casi limite e sono diventati parte del design.",
          code: "// delivered is not processed\nlet message = stream.read().await?;\nif worker.handle(&message).await? {\n    stream.ack(message.id).await?;\n}",
        },
        {
          title: "Prima l'osservabilità, poi la fiducia",
          context: "Un event bus fallisce in silenzio: un messaggio mai elaborato può sembrare identico a uno elaborato.",
          choice: "Trace e log con OpenTelemetry, verso Grafana, Loki e Tempo, prima di costruire altro sopra il bus — così ogni evento si segue da capo a capo e i problemi si trovano dalle prove, non dalle ipotesi.",
        },
      ],
      learned: "Consegnare non è elaborare. Quando le transizioni sono esplicite e osservabili, un sistema event-driven diventa qualcosa su cui si può ragionare — e che si può spiegare a chi ci fa affidamento.",
      stack: [
        "Rust",
        "Tokio",
        "Valkey Streams",
        "S3",
        "OpenTelemetry",
        "Grafana",
        "Loki",
        "Tempo",
        "Spring Boot",
        "React",
      ],
      confidentiality: "Lavoro per un cliente: il cliente, i suoi dati e i dettagli interni sono omessi di proposito.",
    },
  ],

  PULSE: {
    lede: "Attività pubblica reale, presa dall'API di GitHub — quanto rilascio ogni trimestre e con quali linguaggi. Applicazioni web, backend, giochi e strumenti per sviluppatori raccontano aspetti diversi del mio lavoro.",
    takeaway: "Porto una visione sistemica nel lavoro di prodotto: capire il dominio, rendere chiara l'interfaccia e lasciare una codebase più facile da estendere.",
    note: `Generato dall'API di GitHub il ${GITHUB_STATS.generatedAt} da scripts/sync-github.mjs — il calendario dei contributi per il volume, e i commit attribuiti al linguaggio principale di ogni repository per la ripartizione. Il lavoro privato conta nei totali come lo conta GitHub; nessun nome di repository privato viene pubblicato.`,
    forHiringManagers: {
      title: "Come contribuisco",
      points: [
        { label: "Pensiero sistemico", detail: "Collego dominio, asincronia, persistenza e osservabilità senza trattarli come livelli isolati." },
        {
          label: "Consapevolezza del prodotto",
          detail: "Mi interessa l'interfaccia attorno al sistema: flussi chiari, feedback utili e software che si possa continuare a usare.",
        },
        {
          label: "Tooling deliberato",
          detail: "Dalle CLI ai contributi agli editor, cerco strumenti piccoli che eliminino attrito dal lavoro ripetuto.",
        },
        { label: "Collaborazione aperta", detail: "Imparo volentieri in pubblico, ricevo review e rendo i contributi facili da riprendere per altri." },
      ],
    },
    kpis: [
      { label: "GitHub", value: GITHUB_STATS.lastYearContributions, hint: "Contributi, ultimi 12 mesi" },
      { label: "Repository pubblici", value: GITHUB_STATS.publicRepos, hint: `${GITHUB_STATS.totalStars} stelle in totale` },
      { label: "In Luna S.r.l.", display: "Delivery → sistemi", hint: "Dal prodotto rilasciato alla progettazione della piattaforma" },
    ],
    phases: [
      { era: "’24", title: "Università", body: "Vue e TypeScript. Il primo multiplayer a cui gli amici si sono seduti a giocare." },
      { era: "’25", title: "Tirocinio", body: "Java e Spring in produzione. Primo servizio Tokio. Una grammatica per Zed unita." },
      { era: "’26", title: "Lavoro sui sistemi", body: "Servizi Rust, una console operatore Java/React, telemetria live, giochi multiplayer e strumenti per sviluppatori." },
      { era: "Prossimo", title: "Prossimo obiettivo", body: "Kubernetes in produzione. Raft. Un matcher on-chain." },
    ],
  },

  TOOLS: [
    { name: "OpenAI", product: "GPT 6 Sol", href: "https://openai.com", mark: "openai" },
    { name: "Zed", product: "IDE", href: "https://zed.dev", mark: "zed" },
    { name: "Delta", product: "IDE Agente", href: "https://delta.dev", mark: "delta" },
    { name: "GitButler", product: "Client Git", href: "https://gitbutler.com", mark: "gitbutler" },
  ],

  PRINCIPLES: [
    {
      tag: "Capire",
      title: "Trovo il problema reale",
      body: "Prima del codice, capisco a chi serve, come lavora e cosa rende utile il risultato. Lo stack viene dopo il contesto.",
      detail: "Parto dalle persone e dal codice esistente: flussi, vincoli, cosa funziona già e cosa manca. Voglio una definizione condivisa del problema prima di proporre una soluzione, che sia un’interfaccia, un’API o uno strumento per sviluppatori.",
      practice: [
        "Parlo con chi usa o mantiene il software.",
        "Leggo il codice esistente e seguo il flusso interessato dalla modifica.",
        "Chiarisco risultato atteso, vincoli e domande ancora aperte.",
      ],
    },
    {
      tag: "Pianificare",
      title: "Rendo chiaro il prossimo passo",
      body: "Trasformo l’obiettivo in passi piccoli e verificabili. Decido cosa rientra nella modifica, cosa può aspettare e come capire se funziona.",
      detail: "Un piano deve semplificare il lavoro, non diventare un altro progetto. Divido la soluzione in incrementi completi, esplicito dipendenze e compromessi e scelgo strumenti adatti alla codebase e al team.",
      practice: [
        "Definisco perimetro e criteri di accettazione prima di implementare.",
        "Divido il lavoro in modifiche piccole con un ordine chiaro.",
        "Individuo i rischi e come verificare ogni passo.",
      ],
    },
    {
      tag: "Costruire",
      title: "Dall’idea al software che funziona",
      body: "Collego i pezzi, non solo i livelli: dati, logica e interfaccia. Costruisco per piccoli incrementi che si possono eseguire, testare e capire.",
      detail: "Scelgo linguaggio e framework in base al lavoro: Rust per sistemi e tool, Java per applicazioni backend, TypeScript e JavaScript per web e mobile, Python e SQL dove servono. L’obiettivo è una funzionalità completa con confini chiari, non uno stack da esibire.",
      practice: [
        "Seguo le convenzioni esistenti e mantengo le astrazioni mirate.",
        "Costruisco un primo percorso completo prima di allargare il perimetro.",
        "Aggiungo test, gestione degli errori e diagnostica insieme alla funzionalità.",
      ],
    },
    {
      tag: "Review",
      title: "Lo rileggo come se non fosse mio",
      body: "Metto in discussione l’implementazione, verifico i casi limite e rendo ogni diff facile da rivedere. Scrivere codice è solo una parte del lavoro: controllarlo conta altrettanto.",
      detail: "Recentemente ho iniziato a usare Delta.dev per scrivere codice con agenti AI, dedicando molta attenzione alla review. Considero il codice generato una proposta, non un risultato finito: leggo il diff, verifico il design, eseguo i test e chiedo correzioni. La stessa disciplina vale per il codice che scrivo io e per le review con il team.",
      practice: [
        "Leggo ogni diff cercando correttezza, chiarezza e modifiche involontarie.",
        "Eseguo i test pertinenti e verifico anche i percorsi di errore.",
        "Mantengo le modifiche piccole e risolvo il feedback prima del merge.",
      ],
    },
    {
      tag: "Condividere",
      title: "Lascio contesto, non solo codice",
      body: "Spiego cosa è cambiato, perché e come verificarlo. Rendo il lavoro facile da riprendere, anche per chi non usa i miei strumenti.",
      detail: "Delta.dev fa parte del mio workflow, ma il passaggio di consegne non deve dipendere da quello. Porto il contesto utile nelle pull request e nella documentazione: decisioni, compromessi, risultati dei test e punti ancora aperti. Un altro sviluppatore deve poter capire e continuare il lavoro con il proprio editor e un normale workflow Git.",
      practice: [
        "Riassumo nella PR il problema, la soluzione e le ragioni della scelta.",
        "Includo verifiche riproducibili e documento le decisioni importanti accanto al codice.",
        "Esplicito domande aperte e prossimi passi, senza dipendere da una conversazione privata con un agente.",
      ],
    },
  ],

  UI: {
    skipToContent: "Vai al contenuto",
    tocIndex: "Indice",
    tocCurrentWork: "Lavoro attuale",
    tocLanguages: "Lingue parlate",
    tocContact: "Contatti",
    sectionTitles: {
      intro: "Intro",
      experience: "Esperienza",
      projects: "Progetti",
      pulse: "Attività",
      openSource: "Open Source",
      blog: "Blog",
      stack: "Stack",
      futureProjects: "Esplorazioni",
      contact: "Contatti",
      work: "Lavori",
      approach: "Come lavoro",
    },
    close: "Chiudi",
    toggleTheme: "Cambia tema colore",
    openMenu: "Apri il menu",
    closeMenu: "Chiudi il menu",
    contactLede: "Il modo più veloce per raggiungermi è l'email — leggo tutto e rispondo.",
    emailLabel: "Email",
    copyEmail: "Copia indirizzo",
    copiedEmail: "Copiato",
    readThesis: "Leggi la tesi",
  },
};
