import { GITHUB_STATS } from "./github-stats";
import type { SiteData } from "./site.types";

export const EN: SiteData = {
  PROFILE: {
    name: "Alessandro Bruno",
    role: "Software Engineer — Rust / Backend",
    shortRole: "Rust · Backend · Event-driven",
    headline: "Production event-driven services in Rust, from async consumers to traces in Grafana.",
    location: "Bologna, Italy",
    github: "https://github.com/alessandrobrunoh",
    website: "https://alessandrobrunoh.it",
    email: "alessandro.brunoh@gmail.com",
    x: "",
    avatar: "/avatar.jpg",
    company: { name: "Luna S.r.l.", href: "https://lunapartner.it" },
    bio: "Rust backend engineer based in Bologna. For over a year I have worked on production event-driven microservices at Luna S.r.l.: async consumers on Valkey Streams, payloads on S3, and traces and logs through OpenTelemetry into Grafana, Loki and Tempo — all shipped through senior code review. My B.Sc. thesis, PETRA, is an event-driven platform for real-time asynchronous telemetry. Outside work I build tools one layer down: ducklake-orm, a Rust ORM published on crates.io; Mnemosyne, a semantic history for source code built on Tree-sitter; and JDL language support merged into Zed.",
    availability: "Open to Rust and backend roles — remote or hybrid in Italy, available with notice. EU citizen.",
  },

  TOC: [
    { n: "01", href: "#intro", label: "Intro" },
    { n: "02", href: "#projects", label: "Projects" },
    { n: "03", href: "#experience", label: "Experience" },
    { n: "04", href: "#oss", label: "Open Source" },
    { n: "05", href: "#stack", label: "Stack" },
    { n: "06", href: "#contact", label: "Contact" },
  ],

  COMPANY: {
    name: "Luna S.r.l.",
    href: "https://lunapartner.it",
    location: "Bologna, Italy",
    summary:
      "At Luna S.r.l. I started on a fleet platform and, two months in, moved onto the client's production Rust backend under senior code review. Today I work on that event-driven platform and on a new operator console.",
  },

  ROLES: [
    {
      title: "Software Developer",
      dates: "Jun 2026 — present",
      current: true,
      bullets: [
        "Production event-driven Rust services for client workloads: async consumers on Valkey Streams, payloads on S3.",
        "Traces and logs through OpenTelemetry into Grafana, Loki and Tempo.",
        "A new operator console on Spring Boot and React — APIs and UI.",
      ],
      tags: ["Rust", "Tokio", "Valkey Streams", "S3", "OpenTelemetry", "Spring Boot", "React"],
    },
    {
      title: "Software Developer Intern",
      dates: "Sep 2025 — Jun 2026",
      current: false,
      bullets: [
        "Fleet platform in Spring Boot, Angular and React Native, with live updates over WebSockets.",
        "After two months, moved onto the client's Rust backend under senior code review.",
        "Stacked Git branches and small, reviewable diffs as the working norm.",
      ],
      tags: ["Spring Boot", "Angular", "React Native", "WebSocket", "Rust"],
    },
  ],

  EDUCATION: {
    school: "University of Bologna — Cesena Campus",
    degree: "B.Sc. Computer Systems Technologies",
    native: "Tecnologie dei Sistemi Informatici",
    dates: "Graduated 10 Jul 2026",
    thesis: "Design and Development of PETRA, an Event-Driven Platform for Real-Time Asynchronous Telemetry and Analysis",
    // Drop the PDF in /public and set this to "/petra-thesis.pdf" to make it readable.
    thesisHref: "",
  },

  CONTRIBUTIONS: [
    {
      status: "Merged",
      title: "JDL language support",
      repo: "zed-industries/extensions",
      href: "https://github.com/zed-industries/extensions/pull/3339",
      note: "Tree-sitter grammar and editor extension, now in the official marketplace.",
    },
    {
      status: "Open",
      title: "Port forwarding UI and live SSH forwards",
      repo: "zed-industries/zed",
      href: "https://github.com/zed-industries/zed/pull/55248",
      note: "Add or remove forwards on remote sessions without reconnecting.",
    },
    {
      status: "Published",
      title: "ducklake-orm",
      repo: "crates.io",
      href: "https://crates.io/crates/ducklake-orm",
      note: "Rust ORM with derive macros, query builders, pooling, migrations and DuckLake time travel.",
    },
  ],

  PROJECTS: [
    {
      id: "eivar",
      name: "Eivar-Online",
      blurb: "Multiplayer prototype: server-authoritative Rust simulation, replicated state, client-side prediction.",
      href: "https://github.com/alessandrobrunoh/Eivar-Online",
      stars: GITHUB_STATS.stars["Eivar-Online"] ?? 0,
      lang: "Rust",
      meta: "In progress",
      featured: true,
      year: "2026",
      stack: ["Bevy", "SpacetimeDB", "WebAssembly", "Distributed state"],
      highlights: [
        "Server-authoritative simulation with client-side prediction",
        "Replicated state through a SpacetimeDB module compiled to WebAssembly",
        "Loot, gathering, crafting and player markets as bounded domain events",
      ],
      learned:
        "How a game loop maps onto the same event-driven instincts I use at work — the server owns truth, the client only predicts.",
      body: "An open-source multiplayer prototype written in Rust. Bevy ECS runs gameplay; the server owns truth. Recent work covers crowd-control, ability kits, corpse loot, and bounded domain events — the same event-driven instincts I use at work, applied to a living world.",
    },
    {
      id: "mnemosyne",
      name: "Mnemosyne",
      blurb: "Local-first semantic history for source code: symbols and structural changes via Tree-sitter, not line diffs.",
      href: "https://github.com/alessandrobrunoh/Mnemosyne",
      stars: GITHUB_STATS.stars["Mnemosyne"] ?? 0,
      lang: "Rust",
      meta: "Semantic history",
      featured: true,
      year: "2026",
      stack: ["Tree-sitter", "redb", "Content-addressed storage", "MCP"],
      highlights: [
        "Tracks symbols and structural changes instead of line-based diffs",
        "Daemon, CLI and TUI over a content-addressed storage workspace",
        "Exposed to AI tools through MCP",
      ],
      learned: "Shipping a daemon people actually run. Content-addressed storage, a TUI, and the discipline of keeping every byte on-device.",
      body: "The local-history tool I wanted as a daily driver. A daemon watches saves, a TUI and CLI search and restore, and nothing leaves the machine. Still the project that taught me how to ship a Rust tool people actually run.",
    },
    {
      id: "ducklake",
      name: "ducklake-orm",
      blurb: "Rust ORM for DuckDB and DuckLake, published on crates.io — derive macros, query builders, pooling, migrations, time travel.",
      href: "https://github.com/alessandrobrunoh/ducklake-orm",
      stars: GITHUB_STATS.stars["ducklake-orm"] ?? 0,
      lang: "Rust",
      meta: "crates.io",
      featured: true,
      year: "2026",
      stack: ["Rust", "DuckDB", "proc-macro", "SQL"],
      highlights: [
        "Derive macros map structs to tables with zero boilerplate",
        "Type-safe filters, order_by, limit, count, fetch_one",
        "Pooling, migrations, and DuckLake time travel",
      ],
      learned: "The layer under the query: typed boundaries, data ergonomics, and what it takes to make analytical storage feel like a product.",
      body: "A lightweight Rust ORM for DuckDB, built to make analytical storage feel approachable without hiding the useful parts. The work is about typed boundaries, data ergonomics, and the small API decisions that make a tool pleasant to keep using.",
    },
    {
      id: "weaklings",
      name: "Weaklings-Manager",
      blurb: "Self-hosted Albion guild platform — bank, loot splits, battle analytics, Discord login.",
      href: "https://github.com/alessandrobrunoh/Weaklings-Manager",
      stars: GITHUB_STATS.stars["Weaklings-Manager"] ?? 0,
      lang: "Angular",
      meta: "Axum API",
      featured: false,
      year: "2026",
      stack: ["Axum", "PostgreSQL", "Angular", "Discord"],
      highlights: ["Guild bank and loot splits", "Event sessions with battle analytics", "Discord login with role-based access"],
      learned: "A real domain with real users: auth, bank, compositions, and a bot that had to stay up for a guild — not a demo.",
      body: "A Rust/Axum API, an Angular dashboard, and a Discord bot — covering bank, compositions, siphoned-energy tracking, and live Albion data. Built for a guild that needed a real tool, not a spreadsheet.",
    },
    {
      id: "ketchapp",
      name: "KetchApp",
      blurb: "Study productivity as microservices. Pomodoro, AI plans, async notifications.",
      href: "https://github.com/orgs/ketchapp-for-study",
      lang: "Java",
      meta: "Org",
      featured: false,
      year: "2025",
      stack: ["Rust", "Java", "Kafka", "Auth"],
      highlights: ["Auth API in Rust", "Kafka-backed notifications", "Split services instead of a monolith"],
      learned: "Where a monolith breaks. Auth in Rust, notifications on Kafka, and the seams you only see once the pieces move.",
      body: "University team project that became my first real microservices cut: a Rust auth API, a Java Kafka path, and async notifications for Pomodoro and study plans. The org still holds the split.",
    },
    {
      id: "briscola",
      name: "Briscola Online",
      blurb: "Real-time Briscola over WebSockets. Full-stack multiplayer.",
      href: "https://github.com/alessandrobrunoh/Progetto-Ingegneria-Web",
      stars: GITHUB_STATS.stars["Progetto-Ingegneria-Web"] ?? 0,
      lang: "Vue",
      meta: "Web",
      featured: false,
      year: "2024",
      stack: ["Vue", "WebSocket", "Node"],
      highlights: ["Live multiplayer matches", "Responsive table UI", "Persistent game data"],
      learned: "The first time a WebSocket had to stay honest for friends at a table — state, turns, and a UI that could lose.",
      body: "Web engineering coursework that had to actually play. Real-time Briscola over WebSockets, a Vue frontend, and enough backend to keep a match honest. The first time I shipped something friends sat down and used.",
    },
    {
      id: "sdp",
      name: "Semantic Delta Protocol",
      blurb: "Code changes at the AST level — Tree-sitter and structural hashing.",
      href: "https://github.com/alessandrobrunoh/Semantic-Delta-Protocol",
      stars: GITHUB_STATS.stars["Semantic-Delta-Protocol"] ?? 0,
      lang: "Rust",
      meta: "Protocol",
      featured: false,
      year: "2026",
      stack: ["Rust", "Tree-sitter", "JSON-RPC"],
      highlights: ["Symbols instead of line diffs", "Structural hashing that survives refactors", "JSON-RPC surface for editors"],
      learned: "Identity that survives a rename. Tree-sitter walks the AST; hashes keep a function the same function.",
      body: "A protocol for tracking changes at the function and class level, not the line. Tree-sitter walks the AST; structural hashes keep identity through a rename. The research sibling of Mnemosyne.",
    },
    {
      id: "vapt",
      name: "VAPT Research",
      blurb: "Security report on a fork of OWASP Juice Shop.",
      href: "https://github.com/alessandrobrunoh/Relazione-Sicurezza-Privacy",
      lang: "TypeScript",
      meta: "Research",
      featured: false,
      year: "2025",
      stack: ["TypeScript", "OWASP", "VAPT"],
      highlights: ["Forked Juice Shop as the target", "Structured findings, not a scan dump", "Coursework that had to read like a report"],
      learned: "Scope, exploit, impact, fix. Writing like a report, not a leaderboard of CVEs.",
      body: "A vulnerability assessment against a known-broken app, written up as a real report. The point was the method: scope, exploit, impact, fix — not a leaderboard of CVEs.",
    },
  ],

  STACK: {
    groups: [
      {
        name: "Rust",
        level: "Proficient",
        items: "Tokio · Axum · SQLx · Tree-sitter · Bevy",
        also: "Actix, SeaORM, Diesel, clap, ratatui, Leptos, Dioxus, GPUI, wasm-bindgen",
      },
      {
        name: "TypeScript",
        level: "Competent",
        items: "Angular · React · React Native · Node",
        also: "Svelte, Expo, NestJS, Tailwind CSS",
      },
      {
        name: "Java & Python",
        level: "Competent",
        items: "Spring Boot · Hibernate · Maven",
        also: "JHipster, Gradle, Kafka, Python",
      },
      {
        name: "Infrastructure",
        level: "",
        items: "Docker · PostgreSQL · Valkey · S3 · OpenTelemetry · Grafana",
        also: "Linux, Loki, Tempo, Alloy, Redis, DuckLake, Kubernetes",
      },
    ],
  },

  FUTURE_PROJECTS: [
    {
      id: "solana-dex",
      name: "Mini DEX on Solana",
      blurb: "On-chain order matching under blockchain constraints.",
      href: "",
      lang: "Solana",
      meta: "Planned",
      year: "Next",
      stack: ["Rust", "Solana", "Anchor"],
      highlights: [
        "On-chain order book with matching logic in a program",
        "Account-model constraints instead of a free-form database",
        "Compute-budget limits force every instruction to be lean",
      ],
      learned: "How on-chain matching holds up under Solana's account model and compute limits — not just the theory.",
      body: "A DEX order matcher written as a Solana program. The interesting part isn't the matching logic — it's building it inside an account model and compute budget that make you justify every byte and every instruction.",
    },
    {
      id: "btree-db",
      name: "Mini database engine with a B-Tree",
      blurb: "Storage internals — the layer beneath ORMs.",
      href: "https://github.com/alessandrobrunoh/mini-db-btree",
      lang: "Rust",
      meta: "Planned",
      year: "Next",
      stack: ["Rust", "B-Tree", "Storage"],
      highlights: [
        "Page splits, reads, and writes on raw disk pages",
        "No ORM in between — the storage layer itself",
        "A ground-up look at what ducklake-orm sits on top of",
      ],
      learned: "What a B-Tree actually does on disk — page splits, reads, and writes — instead of just calling one through an ORM.",
      body: "A small database engine built around a B-Tree, from scratch. After publishing an ORM, this is the layer beneath it: how data actually gets organized, split, and found on disk.",
    },

  ],

  BLOG: [
    {
      slug: "publishing-a-crate-without-an-audience",
      title: "Making a data tool feel like a product",
      subtitle: "ducklake-orm",
      pitch: "The small API and documentation decisions that turn low-level storage work into something people can actually use.",
      status: "Planned",
      body: [
        "Analytical storage is powerful, but power alone does not make a tool pleasant. I built ducklake-orm to explore the boundary between DuckDB's capabilities and an API that feels clear on an ordinary workday.",
        "The interesting decisions were not only about queries. They were about typed errors, discoverable defaults, migrations, and the point where an abstraction should stop and let the database speak.",
        "This draft will walk through the trade-offs that shaped the API, the documentation I wish I had written first, and the difference between wrapping a system and making it understandable.",
        "The test I keep coming back to is simple: can a new user predict what happens next without opening the implementation? If not, the abstraction is still making the reader pay its complexity tax.",
      ],
    },
    {
      slug: "what-i-got-wrong-about-event-buses",
      title: "What I got wrong about event buses",
      subtitle: "Valkey / internship → hire",
      pitch: "The assumptions I brought from a request/response world into an event-driven one, and where they broke.",
      status: "Planned",
      body: [
        "I came into the Rust backend role from a request/response world — a Spring API that answered a call and moved on. The event bus doesn't work that way, and the assumptions I brought with me were wrong in ways that only showed up under load.",
        "The first one: I treated \"delivered\" and \"processed\" as the same event. They aren't, and the gap between them is where retries, duplicates, and ordering bugs live. Valkey streams make that gap visible if you're willing to look at it.",
        "This is a draft — the finished piece will walk through the specific failure that taught me this, and how observability (Grafana, Alloy, Loki, Tempo) had to be designed in before I trusted the bus enough to build on top of it.",
        "The practical rule became a small state machine: read, handle, acknowledge. Once those transitions were explicit, retries stopped feeling like edge cases and started looking like part of the design.",
      ],
    },
    {
      slug: "reading-a-zed-pr-end-to-end",
      title: "Reading a Zed PR end to end",
      subtitle: "Open source, in practice",
      pitch: "How a real PR moves through review in a fast-moving codebase — what reviewers actually look for.",
      status: "Draft",
      body: [
        "Getting the JDL language extension merged into zed-industries/extensions meant reading Zed's own review process as closely as the code — a fast-moving codebase with strong opinions about what a contribution should look like before a maintainer will even look at it.",
        "The interesting part wasn't the grammar file. It was watching what reviewers actually flagged: naming that didn't match existing conventions, missing test fixtures, and scope creep in a PR that was supposed to do one thing.",
        "This is still a draft. The finished piece walks through the specific review comments on that PR and the newer one still open (dynamic port forwarding), and what they taught me about writing a PR a stranger can approve quickly.",
        "A good review is a compression exercise: the patch should make the intended behavior obvious, keep the diff narrow, and leave the reviewer with one decision instead of ten guesses.",
      ],
    },
  ],

  PULSE: {
    lede: "Real public activity, pulled from the GitHub API — how much I ship each quarter, and what I write it in. The shift from coursework to Rust systems work is the whole story.",
    takeaway: "I bring a systems view to product work: understand the domain, make the interface clear, and leave the codebase easier to extend.",
    note: `Generated from the GitHub API on ${GITHUB_STATS.generatedAt} by scripts/sync-github.mjs — the contribution calendar for volume, and commits attributed by each repository's primary language for the split. Private work counts toward the totals the way GitHub counts it; no private repository name is published.`,
    forHiringManagers: {
      title: "How I contribute",
      points: [
        { label: "Systems thinking", detail: "I connect domain decisions, async execution, persistence, and observability instead of treating them as separate layers." },
        {
          label: "Product awareness",
          detail: "I care about the interface around the system: clear workflows, useful feedback, and software people can keep using.",
        },
        {
          label: "Deliberate tooling",
          detail: "From CLIs to editor contributions, I look for small tools that remove friction from repeated work.",
        },
        { label: "Open collaboration", detail: "I am comfortable learning in public, receiving review, and making a contribution easy for someone else to pick up." },
      ],
    },
    kpis: [
      { label: "GitHub", value: GITHUB_STATS.lastYearContributions, hint: "Contributions, last 12 months" },
      { label: "Public repositories", value: GITHUB_STATS.publicRepos, hint: `${GITHUB_STATS.totalStars} stars across them` },
      { label: "At Luna S.r.l.", display: "Delivery → systems", hint: "Growing from shipped product to platform design" },
    ],
    phases: [
      { era: "’24", title: "University", body: "Vue and TypeScript. First multiplayer that friends sat down and played." },
      { era: "’25", title: "Internship", body: "Java and Spring in production. First Tokio service. A Zed grammar merged." },
      { era: "’26", title: "Systems work", body: "Production event-driven systems, a thesis on live telemetry, and tools that explore the layers beneath." },
      { era: "Next", title: "Aiming at", body: "Kubernetes in production. Raft. An on-chain matcher." },
    ],
  },

  TOOLS: [
    { name: "OpenAI", product: "GPT 6 Sol", href: "https://openai.com", mark: "openai" },
    { name: "Zed", product: "IDE", href: "https://zed.dev", mark: "zed" },
    { name: "Delta", product: "Agent IDE", href: "https://delta.dev", mark: "delta" },
    { name: "GitButler", product: "Git client", href: "https://gitbutler.com", mark: "gitbutler" },
  ],

  UI: {
    skipToContent: "Skip to content",
    tocIndex: "Index",
    tocCurrentWork: "Current work",
    tocLanguages: "Speaking",
    tocContact: "Contact",
    sectionTitles: {
      intro: "Intro",
      experience: "Experience",
      projects: "Projects",
      pulse: "Pulse",
      openSource: "Open Source",
      blog: "Blog",
      stack: "Stack",
      futureProjects: "Exploring",
      contact: "Contact",
    },
    backToBlog: "← Back to Blog",
    postNotFound: "Post not found.",
    close: "Close",
    toggleTheme: "Toggle color theme",
    openMenu: "Open menu",
    closeMenu: "Close menu",
    contactLede: "The fastest way to reach me is email — I read everything and reply.",
    emailLabel: "Email",
    copyEmail: "Copy address",
    copiedEmail: "Copied",
    readThesis: "Read the thesis",
  },
};
